### ISSUE TITLE
Implement reflection

### ISSUE THREAD

**Issue by Andythem23** [Significant-Gravitas/Auto-GPT#11]
_Context:_  Implement  **reflection**, a technique that allows generating more coherent and natural texts using pre-trained language models.

_Problem or idea:_  Reflection is based on two articles that propose different methods to incorporate world knowledge and causal reasoning in text generation. The articles are:

1.  [ArXiv Article](https://arxiv.org/abs/2303.11366)
2.  [GitHub Repository](https://github.com/GammaTauAI/reflexion-human-eval)

_Solution or next step:_  I would like the  _Auto-GPT_  project to include reflection as an option to improve the quality of the generated texts. @Torantulino, what do you think of this idea?

**Comment by Torantulino** [comment]
That it VERY interesting indeed. I've been playing about with getting Auto-GPT to improve itself and write it's own code, this might just be the ticket!

Executing unreviewed AI Generated code is a security risk though, so we'd have to think of the safest way to do this.

Submit a pull request!

**Comment by Andythem23** [comment]
I code but only know about web programming, and I'm a junior too... sorry Haha

**Comment by Torantulino** [comment]
No worries at all, and never let being a junior stop you, the absolute best way to learn is by trying and failing!

**Comment by NotoriousPyro** [comment]
> Executing unreviewed AI Generated code is a security risk though, so we'd have to think of the safest way to do this.

Probably best to have it raise pull requests so that they can be reviewed manually.

**Comment by algopapi** [comment]
I kinda implemented this. However, it is quite tricky because the original paper uses reflection based on ground truth answers. In my impelmentation i let the agent reflect every N steps which can be quite interesting but requires more testing.

**Comment by Bearnardd** [comment]
Around weekend I will do a little bit of research around this topic. @algopapi would you mind sharing your implementation? Have you pushed it on your fork?

**Comment by Bearnardd** [comment]
@LeonardoLGDS I had no time to check the paper yet but I assumed there are some guidelines on benchmarking provided in paper

**Comment by Velocity-** [comment]
If anyone can get me a GPT4 key, either directly via your org with prepayment or by getting me in touch with someone at OpenAI, I'm willing to implement it. I think it could be a lot of fun, and to add an edge, I'll do it on a fresh Linux w/ firewalled access to only the OpenAI API, and a USB chainsaw.

Jk, not the chainsaw.

**Comment by younghuman** [comment]
I'm planning to implement this over the weekend. Another best paper for self-reflection is this: https://arxiv.org/abs/2304.03442

They also have a way of evaluating the agents with some questions.

**Comment by Boostrix** [comment]
> That it VERY interesting indeed. I've been playing about with getting Auto-GPT to improve itself and write it's own code, this might just be the ticket!

I guess, a starting point would be accepting actual constraints/restrictions, aka:
- context window size (restrict to 8k, ideally much less, probably 50% of that)
- restrict changes to a single isolated module (which would mean commands or even better plugins)
- accept that the underlying architecture would then need to work analogous to message passing, and possibly via pipes - anything else won't scale or would change too many places in the source tree at once, basically any agent would consist of a list of other sub-agents, all of which would fork each other as needed (think makefiles/clustering)
- alternatively, come up with a module that can deal with patches/diffs for features spanning multiple files/contexts initially
- to provide sufficient surrounding context, freely use Python docstrings - basically reject PRs that don't have a ton of surrounding context in the form of comments and a ton of unit tests/test coverage
- extend git_operations.py to add support for traversing commit logs (patches + log messages)
- come up with a new plugin to handle github API integration, as per: https://github.com/Significant-Gravitas/Auto-GPT/issues/15#issuecomment-1527964511 
- have unit tests and benchmarks for regression testing purposes
- improve docker integration for CI
- use a custom local LLM to come up with a heatmap (query/idea -> location) that helps identify path/file name and line number based on querying the LLM for an idea/change, so that the agent can determine what set of files/places is likely to be relevant for certain changes, and then narrow down via git logs and commit history
