### ISSUE TITLE
Free API key doesn't work for Auto-GPT access.

### ISSUE THREAD

**Issue by WhispersOfOblivion** [Significant-Gravitas/Auto-GPT#1249]
Help! I don't know how to delete this!

**Comment by hugosmoreira** [comment]
Yeah I just tested has to be the paid one

**Comment by terencebeauj** [comment]
Hi @hugosmoreira, do you know if we need to pay for GPT4 + the paid API key ?
Cause I already have GPT4 access (the paid one), so on top of that, I need to pay for the API key as well ?

**Comment by outjet** [comment]
You will need a credit card on file with https://platform.openai.com because they will bill you for actual usage of the API. It's completely separate from the $20/month Plus membership.
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/24928679/232090485-a48b322e-07f2-4d73-95c2-5934f9255695.png">
