### ISSUE TITLE
Add rich-click CLI

### ISSUE THREAD

**Issue by astelmach01** [Significant-Gravitas/Auto-GPT#1412]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

[Rich-click](https://github.com/ewels/rich-click) allows for a prettier and better CLI tool. This allows us to add a bunch of CLI execution params

### Examples 🌈

![Screenshot 2023-04-14 174611](https://user-images.githubusercontent.com/58709763/232160423-720b4483-2c4b-4199-b823-dd11e33031a5.png)

### Motivation 🔦

Make launching the app easier and with more customizability

**Comment by ntindle** [comment]
@rp-bot are you interested in working on this? Discussing ways to improve user experience is top of mind for me

**Comment by ntindle** [comment]
Dropping my assignment, tag me if you're interested on working on this and I'll help you out

**Comment by Boostrix** [comment]
> I am willing to contribute towards implementing this feature.

FWIW, I started experimenting with a dedicated new command to dynamically set up "wizard" workflows in json and then traversing those workflows using a "prompter" (CLI or GUI). This is then able to by invoked by the agent, but can also invoke the LLM with inputs - it's  basically a handful of new commands to expose this to the LLM, so that it can dynamically set up workflows (in json) and afterwards execute those (possibly in a repeated fashion)

This is all pretty standard/simple stuff, no fancy code at all: 
#3911
![agpt wizard](https://github.com/Significant-Gravitas/Auto-GPT/assets/119627414/54835b15-0b84-464a-8d33-086af542e2b4)

The generated HTML page looks then like this: 
![wizard-app](https://github.com/Significant-Gravitas/Auto-GPT/assets/119627414/fb37b55b-6d8e-4239-8846-0188b300e395)

Also, recursion being recursion, I asked the agent to generate a wizard to generate a new UI based based on the same idea:

#765
![poc-agpt-ui](https://github.com/Significant-Gravitas/Auto-GPT/assets/119627414/ea72136f-4e43-40b1-99fd-7ff9ae648c26)
 
I suppose, someone seriously interested in improving overall usablity could pick up these ideas/PRs and extend those rather quickly using the same approach.
