### ISSUE TITLE
Looking for help managing issues

### ISSUE THREAD

**Issue by p-i-** [Significant-Gravitas/Auto-GPT#1454]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

If there's anyone out there that would be interested in running through issues, compiling a list of ones that can be insta-closed, please reach out. Here or on the Discord (I'm pi@8377).

A large fraction of these issues can be answered, answered+closed, or just closed.

So if someone's able to optionally answer, and compile a list of issues-to-be-closed, our core devs will love you!

**Comment by Qoyyuum** [comment]
Hi, I'd like to volunteer but would like to discuss more to help classify how it needs to be answered and closed. I've added you on Discord under the same username.

**Comment by bjornfix** [comment]
Wouldn't AutoGPT typically be the right one to solve a task like this?

**Comment by p-i-** [comment]
@Qoyyuum  rats I just turned down what I thought were a couple of random friend-requests. If you join the server first https://discord.gg/autogpt you can message me. Please do!

@bjornfix If you can make that work, LMK ;)

**Comment by Qoyyuum** [comment]
Joined and messaged you @p-i- 😉

**Comment by bjornfix** [comment]
@p-i- I'll let you know as soon as I have figured out how to get it to use Pinecone or Redis for memory on my Linux Mint PC here (Yeah, I don't even know how to do that).

**Comment by bjornfix** [comment]
> @p-i- I'll let you know as soon as I have figured out how to get it to use Pinecone or Redis for memory on my Linux Mint PC here (Yeah, I don't even know how to do that).

And now ChatGPT is researching this to pick the best option. Let's see how that goes.

**Comment by bjornfix** [comment]
Oh. It's done. It opted for local and set it in the .env file itself. I did not specify in the goal that Redis is already running locally, so it thought local would be better. 

I'll rerun it, but let it know that Redis is in fact running locally.

**Comment by Explorergt92** [comment]
I can help out .. and try to answer some of the basic basic questions. I've gone threw a bunch to ask the OP if they are still having the issue or if it can be closed

**Comment by JoneKone** [comment]
> Wouldn't AutoGPT typically be the right one to solve a task like this?
Yeah I was actually thinking about the same thing, however.. who's willing to pay for it..

**Comment by Boostrix** [comment]
> Wouldn't AutoGPT typically be the right one to solve a task like this?

The first step would be adding a new plugin to hook up Auto-GPT to the github API, at that point, it could query all sorty of project details, including open issues and help triage those. Different folks/contributors could then run this "mode" to help with reviewing open issues, but also to help with prioritizing issues based on popularity/number of comments etc.

See: https://github.com/Significant-Gravitas/Auto-GPT/issues/15#issuecomment-1527964511
https://github.com/Significant-Gravitas/Auto-GPT/issues/1870#issuecomment-1527959646

**Comment by JoneKone** [comment]
Yeah I'm more than happy to run the plugin, and post result .. ... somewhere. But I'm not able to create the project/plugin.

**Comment by Boostrix** [comment]
> If there's anyone out there that would be interested in running through issues, compiling a list of ones that can be insta-closed, please reach out.

been trying to do just that over the course of the last couple of days in conjunction with @anonhostpi 
I guess, it would help to at least be able to close / re-label some of the more obvious ones.

**Comment by anonhostpi** [comment]
Recommendation to anyone else who wants to join me and @Boostrix turn on "All Notifications" on this repo, and get the GH mobile app (you are going to want it).

There is a new issue/pr/issue comment/pr comment once every minute (I'm not kidding). This is almost a full-time job right now lol.

**Comment by Boostrix** [comment]
at more than 24k forks, the team will happily accept more help - a single day has got 24 hrs, given 24k forks, the next ~1k volunteers stand a pretty damn good chance of making it through the interview (yeah, hurry up).

Seriously, though - roughly 20-30 issues can be closed, and roughly 20 PRs are obsolete/redundant due to lack of coordination between contributors. Some efforts have as many as ~5 different "solutions", which is a pity and a waste of resources.

**Comment by JoneKone** [comment]
how does one apply?

**Comment by Boostrix** [comment]
good question, everybody and their dog seems to mention some, presumably tinder-like app, called "discord" to accelerate the interview process ...

**Comment by JoneKone** [comment]
> good question, everybody and their dog seems to mention some, presumably tinder-like app, called "discord" to accelerate the interview process ...

welp, I won't be joining then =)

**Comment by anonhostpi** [comment]
@JoneKone to be fair, if you hopped on and let them know you were interested, you would very likely get accepted into the role.

Boostrix and I got added on as contributors last week. In a short span of 5 days, I got contributor + member access, and today I just got invited to join the discord moderators. We are very happy to accept help.

We use discord, because we often have conferences, and reading groups to coordinate and share ideas with each other and other GPT communities. An example conference would be the conference we are considering in the next few days/week is with the langchain developer team.

**Comment by Boostrix** [comment]
I don't think that I can currently label issues? 
I was also going to add something to the wiki, but that also wasn't possible - maybe only through a PR? 

FWIW, I acty did try the discord thing, and while I can see/use all sorts of channels, the autogpt invite url does not work for me.

**Comment by anonhostpi** [comment]
> I don't think that I can currently label issues? I was also going to add something to the wiki, but that also wasn't possible - maybe only through a PR?

I think you need the catalyst badge on the discord server

> If you're a member now, any way to suggest that non-code PRs to /docs can be reviewed by folks more easily?

Not exactly at the moment. I'll have to review my perms, but maybe catalysts can do it?

> We also need a team of folks for docker stuff.

Definitely

> Also the codeowners / status stuff is cool but we need to add this to the wiki. We also need to mention what is planned for different parts of the system. Linking up PRs etc

It's a bit difficult to share the team's intentions at the moment, there is so much going on everywhere that it is hard to take time to stop and document our intentions. The team spends a lot of its time in meetings. There was talk about sharing our recorded conversations via youtube. We could maybe then link that to the wiki.

> FWIW, I actually did try the discord thing, and while I can see/use all sorts of channels, the autogpt invite url does not work for me.

What didn't work? You said you could see what's in the server right?

**Comment by Boostrix** [comment]
Like you said, having more people involved in triaging json/docker related issues would be good and would address a bottleneck.

The other bottleneck being the re-arch vs. PR activity, it also seems there are redundant PRs being worked on, as well as RFEs not aware of PRs and vice versa.

I believe, a more "agile" workflow to at least get non-code PRs reviewed more easily might be worth a try - the docker stuff in particular needs a handful of experienced folks to review issues and improve the CI pipeline. If there are concerns, there could be a peer-reviewed branch used for this sort of stuff, before it gets reviewed by the core team. Sort of like the difference between master/stable, just with a focus on non-code changes - i.e. more leeway for tinkering (personally, I would not mind using such a branch).

> It's a bit difficult to share the team's intentions at the moment, there is so much going on everywhere that it is hard to take time to stop and document our intentions. The team spends a lot of its time in meetings. There was talk about sharing our recorded conversations via youtube. We could maybe then link that to the wiki.

Not sure if this is video or audio, but if it's text, I would suggest to try and use GPT to summarize the key points per component. 

The code owners stuff is pretty useful as is, but it would be better if the main people involved in each component could sum up their intentions and open questions, so that the wiki (or some README) can be updated accordingly, even if that should only be a system/folder-specific README that each codeowner maintains. There should maybe be a section at the top/bottom about public interfaces required, but the rest would be internal anyway.

For instance, re-arch wise, I am still looking for authoritative info on things like 1) task planning and 2) workspace/tasking persistence - and based on my experiments I probably have some things that I could contribute from my perspective

Again, I am not sure how many people are actively involved - so this may be way off, but depending on the degree of activity, we need to figure out a model that works for the level of involvement of different folks. And at the very least, people should be able to sum up what they agree/disagree on or what's there in terms of open questions, i.e. what needs to be discussed. 

It doesn't need to be set in stone, but there needs to be a discussion and a document that updates the current state of things so that people can think about it, especially at the boundaries to other components/systems.


> What didn't work? You said you could see what's in the server right?

I can use discord in general, it's just the autogpt invite that isn't working, and it kinda looks like a really fancy Netflix version of IRC on steroids as depicted in "Back from the Future"

**Comment by anonhostpi** [comment]
https://discord.gg/autogpt

can you share a screenshot?

**Comment by Boostrix** [comment]
probably not the right place, but we can delete this stuff later on

![unable](https://github.com/Significant-Gravitas/Auto-GPT/assets/119627414/6e15df96-a86f-4a0b-8b2c-3bdd1e5f5180)

**Comment by Boostrix** [comment]
another issue that probably should never be closed, we really need a label for those and teach the bot to ignore such issues
