### ISSUE TITLE
Cookies selected instead of page content on google'ing

### ISSUE THREAD

**Issue by piotr-mamenas** [Significant-Gravitas/Auto-GPT#1546]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Ask autoGPT to assemble some list (example: investors list, client list, whatever)

### Current behavior 😯
When googling for data:

SYSTEM:  Command browse_website returned: ("Answer gathered from website: The text does not provide information abou
t the XYZ. It explains how TechCrunch uses cookies for their websites and apps, and how users can manage their privacy settings.

Pops up very often even through the website has information. The reason is the cookies popup content is selected for analysis instead of actual content of the page.

### Expected behavior 🤔

autoGPT reads the page and gathers data from it

**Comment by Timmermanzzz** [comment]
same here, what to do about it

**Comment by Neel738** [comment]
same here - it doesn't seem to work

**Comment by gpayer** [comment]
I added the sentence "Ignore content from cookie consent popups, ads and disclaimers." to line 131 in  autogpt/processing/text.py.
So far I didn't have anymore problems with cookie banners, but I haven't tested much. More often than not I ran into the "too much tokens" problem.

**Comment by R037** [comment]
An easy fix is to use a VPN.

**Comment by japppie** [comment]
I'm having the same issue on nearly all websites. Whenever a cookie wall appears or even a 'subscribe to our newsletter' pop-up appears on the page, AutoGPT only reads inside those containers.
How can I make AutoGPT ignore cookie walls and those other pop-ups when scraping a website?

**Comment by Bubble007** [comment]
same problem

**Comment by jeffmercury** [comment]
Any update on this, I have the same issue where AutoGPT just scrapes pop up’s and doesn't read the whole page

**Comment by jeffmercury** [comment]
I fixed this by configuring my Selenium class to close the pop up before it reads.

**Comment by jeffmercury** [comment]
Also use the disable pop up option. Use chat gpt to figure out how to implement this

**Comment by FarzanT** [comment]
@jeffmercury Thank you! Are you interested in a PR?

**Comment by jeffmercury** [comment]
Hi FarzanT yes

**Comment by Bubble007** [comment]
Hi @jeffmercury Can you please explain, what exactly to do for "fixed this by configuring my Selenium class to close the pop up before it reads"

**Comment by jeffmercury** [comment]
Before trying my solution, I would like to state that a better way is to see if you can get the data you want as JSON from an API, instead of having to scrape the web for your information which introduces a lot of errors. That's what I'm doing otherwise try my solution below


This solution is not a guaranteed and requires some configuration. It will not work in Docker. There are two ways to disable pops ups. Adding the --disable-popup-blocking option to selenium or have selenium close the pop up by clicking it close button. 

First update your .ENV with this :
 HEADLESS_BROWSER=True
 USE_WEB_BROWSER=chrome

First Option: 

Then in your web_selenium.py find the scrape_text_with_seleniumfunction  and add this : 

options.add_argument("--disable-popup-blocking")

This should disable normal pop ups, however If pop-ups still persist, they might be implemented in a way that is not recognized as a standard JavaScript alert by Selenium. In this case, you would need to identify the specific HTML element of the pop-up and interact with it (e.g., click a close button).


Second Option:

Add this to the scrape_text_with_seleniumfunction() in the web_selenium.py file  right after this  driver.get(url) .

#If the pop up is a dialog box that cant be closed with the --disable-popup-blocking, find the close button and click it

    try:
        wait = WebDriverWait(driver, 2)
        close_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '#sds-dialog-0 > layout-splash-modal > div.grid-row.flex-column.tablet\:flex-row > div:nth-child(2) > div > button')))
        close_button.click()
    except Exception as e:
        print(f"Error interacting with the close button: {e}")


Here we are telling selenium to wait 2 seconds then hit the pop ups close button. Use the browser tools to get the close button of your pop up CSS selector and pass it to the function above like I  did. 

Ensure you are using manual mode and explicitly tell the AI to use the browse_website function with questions on what to read on the page as arguments. If you get stuck, use chat gpt to help you, this is how I came up with this solution.
 
@Bubble007

**Comment by Bubble007** [comment]
Hi @jeffmercury, thank you very much. I think. that helps many. :-)

**Comment by bluelancer** [comment]
Confirm the issue as well

**Comment by j0schi** [comment]
same here, seems like there is no easy solution available exept for moving the server...
