### ISSUE TITLE
Create tasks for the user/ a employee

### ISSUE THREAD

**Issue by syntex01** [Significant-Gravitas/Auto-GPT#156]
Gpt4 could create tasks for the user in a list. For example if it is ordered to invent and create a dish, it could give the user the links of where to buy the groceries from and then instruct him on how to make the dish. Similarly it could manage the taks of employees in this way.

**Comment by qsmits** [comment]
Indeed! A way to differentiate between a 'command' for GPT and a request from the user would be great.

I've been using it to do research and it often asks for user input to rate the usefulness of its results from 1-5.

However, I often let it run 10-20 commands at a time. If there is no user feedback, it will start an agent to get feedback from, which will tell it that it cannot provide feedback on the usefulness, since it is a language model. It will then go into a loop, trying a couple of times before giving up and trying to get more information on the topic via Google.

**Comment by Qoyyuum** [comment]
Sounds like an interesting discussion. Please bring it to https://github.com/Significant-Gravitas/Auto-GPT/discussions. Closing this issue.
