### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Nikilites** [Significant-Gravitas/Auto-GPT#1565]
### Duplicates

- [x] I have searched the existing issues

### Steps to reproduce 🕹

When i try `python -m autogpt` (i done all the steps) the cmd send me this: 

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Users\censured\Desktop\AUTO-GPT\Auto-GPT\autogpt\__main__.py", line 12, in <module>
    from autogpt import commands as cmd
  File "D:\Users\censured\Desktop\AUTO-GPT\Auto-GPT\autogpt\commands.py", line 7, in <module>
    from autogpt.web import browse_website
  File "D:\Users\censured\Desktop\AUTO-GPT\Auto-GPT\autogpt\web.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'`

### Current behavior 😯

It should work, but it doesn't

### Expected behavior 🤔

It should start the program

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by nponeccop** [comment]
This is unfortunate, as we move fast and break things. Which version did you use? Did you clone master or stable? Did you download the yesterday release?

**Comment by DarkShadowG** [comment]
i am also getting similar errors : 
`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/darkshadow/Auto-GPT/autogpt/__main__.py", line 3, in <module>
    from autogpt.agent.agent import Agent
  File "/home/darkshadow/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/home/darkshadow/Auto-GPT/autogpt/agent/agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "/home/darkshadow/Auto-GPT/autogpt/app.py", line 22, in <module>
    from autogpt.processing.text import summarize_text
  File "/home/darkshadow/Auto-GPT/autogpt/processing/text.py", line 3, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver
ModuleNotFoundError: No module named 'selenium'
`

**Comment by orrbit82** [comment]
run `pip install -r requirements.txt` again and it should work

**Comment by Boberttt** [comment]
or use pip install selenium

**Comment by DarkShadowG** [comment]
> run `pip install -r requirements.txt` again and it should work

I have done this :`Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (4.11.2)
Requirement already satisfied: colorama==0.4.6 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: openai==0.27.2 in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.27.2)
Requirement already satisfied: playsound==1.2.2 in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.2.2)
Requirement already satisfied: python-dotenv==1.0.0 in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.0.0)
Requirement already satisfied: pyyaml==6.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (6.0)
Requirement already satisfied: readability-lxml==0.8.1 in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (0.8.1)
Requirement already satisfied: requests in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (2.28.2)
Requirement already satisfied: tiktoken==0.3.3 in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (0.3.3)
Requirement already satisfied: gTTS==2.3.1 in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2.3.1)
Requirement already satisfied: docker in /usr/lib/python3/dist-packages (from -r requirements.txt (line 11)) (5.0.3)
Requirement already satisfied: duckduckgo-search in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (2.8.5)
Requirement already satisfied: google-api-python-client in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (2.85.0)
Requirement already satisfied: pinecone-client==2.2.1 in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (2.2.1)
Requirement already satisfied: redis in /usr/lib/python3/dist-packages (from -r requirements.txt (line 15)) (4.3.4)
Requirement already satisfied: orjson in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (3.8.10)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 17)) (9.2.0)
Requirement already satisfied: selenium in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (4.8.3)
Requirement already satisfied: webdriver-manager in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 19)) (3.8.6)
Requirement already satisfied: coverage in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 20)) (7.2.3)
Requirement already satisfied: flake8 in /home/darkshadow/.local/lib/python3.10/site-packages (from -r requirements.txt (line 21)) (6.0.0)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from -r requirements.txt (line 22)) (1.21.5)
Collecting pre-commit
  Using cached pre_commit-3.2.2-py2.py3-none-any.whl (202 kB)
Collecting black
  Using cached black-23.3.0-py3-none-any.whl (180 kB)
ERROR: Could not find a version that satisfies the requirement sourcery (from versions: none)
ERROR: No matching distribution found for sourcery   ` But its still giving me the same error when i try to run autogpt: `Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/darkshadow/Auto-GPT/autogpt/__main__.py", line 3, in <module>
    from autogpt.agent.agent import Agent
  File "/home/darkshadow/Auto-GPT/autogpt/agent/__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "/home/darkshadow/Auto-GPT/autogpt/agent/agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "/home/darkshadow/Auto-GPT/autogpt/app.py", line 22, in <module>
    from autogpt.processing.text import summarize_text
  File "/home/darkshadow/Auto-GPT/autogpt/processing/text.py", line 3, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver
ModuleNotFoundError: No module named 'selenium'
`

**Comment by sudouser777** [comment]
@Nikilites did you installed the newly added modules in requirements.txt, if not try running this command `pip install -r requirements.txt`

**Comment by hubertdungen** [comment]
I have similar problems when trying to run "python -m autogpt --speak --gpt3only"
and tried everything you told here and nothing solves.

The error I get:
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\huber\Documents\Auto-GPT\Auto-GPT\autogpt\__main__.py", line 3, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'`

**Comment by sudouser777** [comment]
@hubertdungen try this command it will reinstall all the modules `pip install --force-reinstall -r requirements.txt`

**Comment by DarkShadowG** [comment]
> @hubertdungen try this command it will reinstall all the modules `pip install --force-reinstall -r requirements.txt`
doesn't work for me still

**Comment by sudouser777** [comment]
Which branch are you using? Do you have the latest changes in your code?

**Comment by DarkShadowG** [comment]
> Which branch are you using? Do you have the latest changes in your code?

yeah I have. I just fixed my problem selenium wasn't working for me so i install selenium using pip3 install -U selenium and it worked for me

**Comment by ivaylogrind** [comment]
I have the same problem with Macbook M2 processor. 
I am trying with both of the branches - master and stable

On master I can't install the requirements.txt due to the following error: 
ERROR: Could not build wheels for grpcio, grpcio-tools, which is required to install pyproject.toml-based projects

On the stable branch, I can install it but when I try to run it I am receiving the following error: 
Auto-GPT % python -m autogpt
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ivaylokarmazov/Desktop/autochatgtp/2/Auto-GPT/autogpt/__main__.py", line 6, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'

Any ideas?

**Comment by mabry1985** [comment]
Same problem running native ubuntu

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/Auto-GPT/autogpt/__main__.py", line 3, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

**Comment by mabry1985** [comment]
running pip install with `python -m` seems to have done the trick in my case
`python -m pip install -r requirements.txt`

**Comment by Qoyyuum** [comment]
and if `colorama` error shows up still, `pip install colorama` will work too.

@Nikilites please confirm if there's no more issue after trying any of the suggested solution stated above.

**Comment by nickali** [comment]
I'm on an Intel Mac Pro running Monterey.

```python -m pip install -r requirements.txt``` worked for me.

**Comment by TBKJoshua** [comment]
> running pip install with `python -m` seems to have done the trick in my case `python -m pip install -r requirements.txt`

Thanks a lot! I had a similar issue but it was for 'no module named <openai>', even though I had it installed.


PS: I tried this command "pip install --force-reinstall -r requirements.txt" from @sudouser777 before I tried yours in case that helps anyone.

**Comment by Tomchl01** [comment]
Same here, I've tried to force reinstall requirements, and shows all satisfied but still getting this error on Windows - python environment 
PS C:\Auto-GPT-master> & C:/Users/Mark1/AppData/Local/Programs/Python/Python311/python.exe c:/Auto-GPT-master/autogpt/__main__.py
Traceback (most recent call last):
  File "c:\Auto-GPT-master\autogpt\__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
ModuleNotFoundError: No module named 'autogpt'

**Comment by Nikilites** [comment]
> running pip install with `python -m` seems to have done the trick in my case `python -m pip install -r requirements.txt`

The problem, that i just see, is that the python can't download the Wheel for grpcio, is the only problem

**Comment by ntindle** [comment]
Try and use the #tech-support channel in discord for these issues. We don’t have the capacity to help debug in GitHub issues for problems like this

**Comment by dierucin** [comment]
> running pip install with `python -m` seems to have done the trick in my case `python -m pip install -r requirements.txt`

This Works.
And the pip need to be updated to the latest version.

**Comment by marfotony** [comment]
This worked for me....
`python3 -m pip install -r requirements.txt`

**Comment by randyb100** [comment]
> @hubertdungen try this command it will reinstall all the modules `pip install --force-reinstall -r requirements.txt`

This worked for me after using https://github.com/Significant-Gravitas/Auto-GPT/issues/1517 and https://github.com/Significant-Gravitas/Auto-GPT/discussions/2044#discussioncomment-5643238 besides step 5. I modified web.py and then did the force reinstall and it works great!

I'm actually running it in Google Colab and have to do the pip install every time I want to run it, but it's a lot faster than a local install since I don't have an RTX card. Thanks for the help.
