### ISSUE TITLE
API Bad gateway error

### ISSUE THREAD

**Issue by SimonReichmann** [Significant-Gravitas/Auto-GPT#1599]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Starting AutoGPT via 

python -m autogpt
or 
python -m autogpt -- debug

### Current behavior 😯

![grafik](https://user-images.githubusercontent.com/75829931/232231189-50fdccdd-0efa-4b8a-a093-af12e9389df1.png)

### Expected behavior 🤔

It should start normally

### Your prompt 📝

```yaml
python -m autogpt -- debug
```

**Comment by Yomgui22** [comment]
+1

**Comment by missge9** [comment]
+1

**Comment by user-will** [comment]
A bad gateway error usually occurs when the server is down or overloaded. It is likely an issue on their side that will be resolved shortly. I would recommend just giving it some time and trying again later.

**Comment by frozenranger** [comment]
same issue :(

**Comment by UserHIJ** [comment]
+1

**Comment by SimonReichmann** [comment]
Ok, I didn't realize that GPT Plus and a paid API Account were different things. It works now.

**Comment by UserHIJ** [comment]
yeah , I figured this. but this message should be cleaned up no? a bad gateway and an api account error are two different things..

**Comment by DrewBruce** [comment]
+1 Same error

**Comment by UserHIJ** [comment]
I guess when we report this now we need to share whether are not we're using a paid OPEN AI API Key. Cause switching to that worked for me . Another good clue is go into OpenAI billing and see if your billing is even being hit.

**Comment by saviodamato** [comment]
I have a paid account, I created a new key, I already installed and uninstalled it, I didn't reach the limit and still this problem is happening. This actually started happening when I created the paid account. When I was using only the free credits, it was working. When I realized that the free credits were about to run out, I added a paid account and entered a new key. After that it didn't work anymore. I have installed and uninstalled several times and the error persists. As this forum is a few weeks old, it is a recurring problem. Has anyone managed to resolve?
-----------------------------------------------------------------------
Creating chat completion with model gpt-3.5-turbo, temperature 0.0, max_tokens 2510
Reached rate limit, passing...  Error:
You can read more here: https://docs.agpt.co/setup/#getting-an-api-key
API Bad gateway. Waiting 4 seconds...  Error:
Reached rate limit, passing...  Error:
API Bad gateway. Waiting 8 seconds...  Error:
Reached rate limit, passing...  Error:
API Bad gateway. Waiting 16 seconds...  Error:
Reached rate limit, passing...  Error:
-----------------------------------------------------------

**Comment by anonhostpi** [comment]
Define "reach the limit." There are multiple limits on OpenAI accounts. There is the financial limit, and the rate limit. You may have not reached your financial limit, but you may have reached your rate limit, expecially if you frequently use your OpenAI account. OpenAI limits the amount of requests and tokens you can process per minute/hr
