### ISSUE TITLE
Could not build wheels for grpcio, grpcio-tools, mmh3, ujson, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Nickonomic** [Significant-Gravitas/Auto-GPT#1624]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

error: subprocess-exited-with-error

  × Building wheel for ujson (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      C:\Users\beley\AppData\Local\Temp\pip-build-env-qi7_y794\overlay\Lib\site-packages\setuptools\config\setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_ext
      building 'ujson' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ 
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ujson
Failed to build grpcio grpcio-tools mmh3 ujson
ERROR: Could not build wheels for grpcio, grpcio-tools, mmh3, ujson, which is required to install pyproject.toml-based projects

### Current behavior 😯

The program doesn't start after the recent upgrades. 'Couldn't build wheels'.  Latest Microsoft Visual C++ is installed.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by killepi** [comment]
Same error here.

**Comment by hugomn** [comment]
Same error here trying to install on mac arm processor:

```
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/openssl@3/include -I/opt/homebrew/opt/re2/include -DHAVE_PTHREAD=1 -I. -Igrpc_root -Igrpc_root/include -Ithird_party/protobuf/src -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c third_party/protobuf/src/google/protobuf/util/time_util.cc -o build/temp.macosx-13-arm64-cpython-311/third_party/protobuf/src/google/protobuf/util/time_util.o -std=c++14 -fno-wrapv -frtti
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/openssl@3/include -I/opt/homebrew/opt/re2/include -DHAVE_PTHREAD=1 -I. -Igrpc_root -Igrpc_root/include -Ithird_party/protobuf/src -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c third_party/protobuf/src/google/protobuf/util/type_resolver_util.cc -o build/temp.macosx-13-arm64-cpython-311/third_party/protobuf/src/google/protobuf/util/type_resolver_util.o -std=c++14 -fno-wrapv -frtti
      1 warning generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio-tools
  Running setup.py clean for grpcio-tools
Failed to build grpcio grpcio-tools
ERROR: Could not build wheels for grpcio, grpcio-tools, which is required to install pyproject.toml-based projects
```

**Comment by EeeDotZee** [comment]
Having the same error on while trying to run `pip3 install -r requirements.txt`
Output:
`ERROR: Failed building wheel for grpcio-tools
  Running setup.py clean for grpcio-tools
Failed to build grpcio grpcio-tools
ERROR: Could not build wheels for grpcio, grpcio-tools, which is required to install pyproject.toml-based projects`

**Comment by Qoyyuum** [comment]
Hi @Nickonomic the error says

> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

That means you have to install Microsoft Visual C++ 14.0 or greater and you can get it via Microsoft C++ Build Tools via that link it provided.

**Comment by scottswaaley** [comment]
No promises but I was getting a related error and it ended up going away once I downgraded to Python 3.9.13.

**Comment by killepi** [comment]
With installed Visal C++:

Microsoft Windows [Version 10.0.22621.1555]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Kilia\Documents\AI\autoGPT\Auto-GPT>pip install -r requirements.txt
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting colorama==0.4.6
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting openai==0.27.2
  Using cached openai-0.27.2-py3-none-any.whl (70 kB)
Requirement already satisfied: playsound==1.2.2 in c:\users\kilia\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 4)) (1.2.2)
Collecting python-dotenv==1.0.0
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting pyyaml==6.0
  Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
Collecting readability-lxml==0.8.1
  Using cached readability_lxml-0.8.1-py3-none-any.whl (20 kB)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting tiktoken==0.3.3
  Using cached tiktoken-0.3.3-cp310-cp310-win_amd64.whl (579 kB)
Collecting gTTS==2.3.1
  Using cached gTTS-2.3.1-py3-none-any.whl (28 kB)
Collecting docker
  Using cached docker-6.0.1-py3-none-any.whl (147 kB)
Collecting duckduckgo-search
  Using cached duckduckgo_search-2.8.6-py3-none-any.whl (30 kB)
Collecting google-api-python-client
  Using cached google_api_python_client-2.85.0-py2.py3-none-any.whl (11.2 MB)
Collecting pinecone-client==2.2.1
  Using cached pinecone_client-2.2.1-py3-none-any.whl (177 kB)
Collecting pymilvus==2.2.4
  Using cached pymilvus-2.2.4-py3-none-any.whl (128 kB)
Collecting redis
  Using cached redis-4.5.4-py3-none-any.whl (238 kB)
Collecting orjson
  Using cached orjson-3.8.10-cp310-none-win_amd64.whl (197 kB)
Collecting Pillow
  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting selenium
  Using cached selenium-4.8.3-py3-none-any.whl (6.5 MB)
Collecting webdriver-manager
  Using cached webdriver_manager-3.8.6-py2.py3-none-any.whl (27 kB)
Collecting coverage
  Using cached coverage-7.2.3-cp310-cp310-win_amd64.whl (203 kB)
Collecting flake8
  Using cached flake8-6.0.0-py2.py3-none-any.whl (57 kB)
Collecting sentence_transformers
  Downloading sentence-transformers-2.2.2.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy
  Using cached numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting pre-commit
  Using cached pre_commit-3.2.2-py2.py3-none-any.whl (202 kB)
Collecting black
  Using cached black-23.3.0-cp310-cp310-win_amd64.whl (1.3 MB)
Requirement already satisfied: sourcery in c:\users\kilia\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 27)) (1.2.0)
Collecting isort
  Using cached isort-5.12.0-py3-none-any.whl (91 kB)
Collecting gitpython==3.1.31
  Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 11.6 MB/s eta 0:00:00
Collecting tqdm
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting aiohttp
  Using cached aiohttp-3.8.4-cp310-cp310-win_amd64.whl (319 kB)
Collecting lxml
  Using cached lxml-4.9.2-cp310-cp310-win_amd64.whl (3.8 MB)
Collecting cssselect
  Using cached cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Collecting chardet
  Using cached chardet-5.1.0-py3-none-any.whl (199 kB)
Collecting regex>=2022.1.18
  Using cached regex-2023.3.23-cp310-cp310-win_amd64.whl (267 kB)
Collecting click<8.2,>=7.1
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting python-dateutil>=2.5.3
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting dnspython>=2.0.0
  Using cached dnspython-2.3.0-py3-none-any.whl (283 kB)
Collecting urllib3>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting loguru>=0.5.0
  Using cached loguru-0.7.0-py3-none-any.whl (59 kB)
Collecting grpcio<=1.48.0,>=1.47.0
  Using cached grpcio-1.47.5-cp310-cp310-win_amd64.whl (3.5 MB)
Collecting grpcio-tools<=1.48.0,>=1.47.0
  Using cached grpcio_tools-1.47.5-cp310-cp310-win_amd64.whl (1.9 MB)
Collecting pandas>=1.2.4
  Using cached pandas-2.0.0-cp310-cp310-win_amd64.whl (11.2 MB)
Collecting mmh3<=3.0.0,>=2.0
  Using cached mmh3-3.0.0.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting ujson<=5.4.0,>=2.0.0
  Using cached ujson-5.4.0-cp310-cp310-win_amd64.whl (37 kB)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB ? eta 0:00:00
Collecting soupsieve>1.2
  Using cached soupsieve-2.4-py3-none-any.whl (37 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting packaging>=14.0
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting websocket-client>=0.32.0
  Using cached websocket_client-1.5.1-py3-none-any.whl (55 kB)
Requirement already satisfied: pywin32>=304 in c:\users\kilia\appdata\local\programs\python\python310\lib\site-packages (from docker->-r requirements.txt (line 11)) (306)
Collecting google-auth<3.0.0dev,>=1.19.0
  Using cached google_auth-2.17.3-py2.py3-none-any.whl (178 kB)
Collecting uritemplate<5,>=3.0.1
  Using cached uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Collecting httplib2<1dev,>=0.15.0
  Using cached httplib2-0.22.0-py3-none-any.whl (96 kB)
Collecting google-auth-httplib2>=0.1.0
  Using cached google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Using cached google_api_core-2.11.0-py3-none-any.whl (120 kB)
Collecting async-timeout>=4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting trio-websocket~=0.9
  Using cached trio_websocket-0.10.2-py3-none-any.whl (17 kB)
Collecting trio~=0.17
  Using cached trio-0.22.0-py3-none-any.whl (384 kB)
Collecting mccabe<0.8.0,>=0.7.0
  Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting pycodestyle<2.11.0,>=2.10.0
  Using cached pycodestyle-2.10.0-py2.py3-none-any.whl (41 kB)
Collecting pyflakes<3.1.0,>=3.0.0
  Using cached pyflakes-3.0.1-py2.py3-none-any.whl (62 kB)
Collecting transformers<5.0.0,>=4.6.0
  Downloading transformers-4.28.1-py3-none-any.whl (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 24.7 MB/s eta 0:00:00
Collecting torch>=1.6.0
  Downloading torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.3/172.3 MB 26.2 MB/s eta 0:00:00
Collecting torchvision
  Downloading torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 79.0 MB/s eta 0:00:00
Collecting scikit-learn
  Downloading scikit_learn-1.2.2-cp310-cp310-win_amd64.whl (8.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 58.8 MB/s eta 0:00:00
Collecting scipy
  Downloading scipy-1.10.1-cp310-cp310-win_amd64.whl (42.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 MB 50.1 MB/s eta 0:00:00
Collecting nltk
  Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 100.0 MB/s eta 0:00:00
Collecting sentencepiece
  Downloading sentencepiece-0.1.98-cp310-cp310-win_amd64.whl (977 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 977.8/977.8 kB 64.5 MB/s eta 0:00:00
Collecting huggingface-hub>=0.4.0
  Downloading huggingface_hub-0.13.4-py3-none-any.whl (200 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 12.7 MB/s eta 0:00:00
Collecting nodeenv>=0.11.1
  Using cached nodeenv-1.7.0-py2.py3-none-any.whl (21 kB)
Collecting identify>=1.0.0
  Using cached identify-2.5.22-py2.py3-none-any.whl (98 kB)
Collecting cfgv>=2.0.0
  Using cached cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting virtualenv>=20.10.0
  Using cached virtualenv-20.21.0-py3-none-any.whl (8.7 MB)
Collecting platformdirs>=2
  Using cached platformdirs-3.2.0-py3-none-any.whl (14 kB)
Collecting pathspec>=0.9.0
  Using cached pathspec-0.11.1-py3-none-any.whl (29 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting tomli>=1.1.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting googleapis-common-protos<2.0dev,>=1.56.2
  Using cached googleapis_common_protos-1.59.0-py2.py3-none-any.whl (223 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5
  Using cached protobuf-4.22.3-cp310-abi3-win_amd64.whl (420 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting six>=1.9.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Requirement already satisfied: setuptools in c:\users\kilia\appdata\local\programs\python\python310\lib\site-packages (from grpcio-tools<=1.48.0,>=1.47.0->pymilvus==2.2.4->-r requirements.txt (line 15)) (65.5.0)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5
  Using cached protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
Collecting pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting filelock
  Using cached filelock-3.11.0-py3-none-any.whl (10.0 kB)
Collecting win32-setctime>=1.0.0
  Using cached win32_setctime-1.1.0-py3-none-any.whl (3.6 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\kilia\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.2.4->pymilvus==2.2.4->-r requirements.txt (line 15)) (2023.3)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting sympy
  Downloading sympy-1.11.1-py3-none-any.whl (6.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 59.3 MB/s eta 0:00:00
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB ? eta 0:00:00
Collecting networkx
  Downloading networkx-3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 66.5 MB/s eta 0:00:00
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Downloading tokenizers-0.13.3-cp310-cp310-win_amd64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 36.8 MB/s eta 0:00:00
Collecting async-generator>=1.9
  Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Collecting cffi>=1.14
  Using cached cffi-1.15.1-cp310-cp310-win_amd64.whl (179 kB)
Requirement already satisfied: sortedcontainers in c:\users\kilia\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium->-r requirements.txt (line 19)) (2.4.0)
Collecting outcome
  Using cached outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Collecting attrs>=19.2.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting exceptiongroup>=1.0.0rc9
  Using cached exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting sniffio
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting wsproto>=0.14
  Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting PySocks!=1.5.7,<2.0,>=1.5.6
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting distlib<1,>=0.3.6
  Using cached distlib-0.3.6-py2.py3-none-any.whl (468 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.8.2-cp310-cp310-win_amd64.whl (56 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.3-cp310-cp310-win_amd64.whl (33 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.4-cp310-cp310-win_amd64.whl (28 kB)
Collecting joblib
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 18.0 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\kilia\appdata\local\programs\python\python310\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.19.0->google-api-python-client->-r requirements.txt (line 13)) (0.4.8)
Collecting h11<1,>=0.9.0
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting mpmath>=0.19
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB ? eta 0:00:00
Installing collected packages: tokenizers, sentencepiece, mpmath, mmh3, distlib, win32-setctime, websocket-client, urllib3, uritemplate, ujson, tzdata, typing-extensions, tomli, threadpoolctl, sympy, soupsieve, sniffio, smmap, six, rsa, regex, pyyaml, python-dotenv, PySocks, pyparsing, pyflakes, pycparser, pycodestyle, pyasn1-modules, protobuf, platformdirs, Pillow, pathspec, packaging, orjson, numpy, nodeenv, networkx, mypy-extensions, multidict, mccabe, MarkupSafe, lxml, joblib, isort, idna, identify, h11, frozenlist, filelock, exceptiongroup, dnspython, cssselect, coverage, colorama, charset-normalizer, chardet, cfgv, certifi, cachetools, attrs, async-timeout, async-generator, yarl, wsproto, virtualenv, tqdm, scipy, requests, redis, readability-lxml, python-dateutil, outcome, loguru, jinja2, httplib2, grpcio, googleapis-common-protos, google-auth, gitdb, flake8, click, cffi, beautifulsoup4, aiosignal, webdriver-manager, trio, torch, tiktoken, scikit-learn, pre-commit, pinecone-client, pandas, nltk, huggingface-hub, gTTS, grpcio-tools, google-auth-httplib2, google-api-core, gitpython, duckduckgo-search, docker, black, aiohttp, trio-websocket, transformers, torchvision, pymilvus, openai, google-api-python-client, sentence_transformers, selenium
  DEPRECATION: mmh3 is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for mmh3 ... error
  error: subprocess-exited-with-error

  × Running setup.py install for mmh3 did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      C:\Users\Kilia\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'mmh3' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> mmh3

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by JTemmink** [comment]
> No promises but I was getting a related error and it ended up going away once I downgraded to Python 3.9.13.

Worked with me! Thanks!

**Comment by killepi** [comment]
Reinstalling all Microsoft Visual Studio Build Tools (2022) worked for me.

**Comment by Nickonomic** [comment]
> Reinstalling all Microsoft Visual Studio Build Tools (2022) worked for me.

Did you delete the old version? Or just install this on top?

**Comment by Nickonomic** [comment]
> Hi @Nickonomic the error says
> 
> > error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> 
> That means you have to install Microsoft Visual C++ 14.0 or greater and you can get it via Microsoft C++ Build Tools via that link it provided.

Installed the latest Visual C++ and Microsoft C++ Build Tools (2022). Still doesn't work. Forgot to mention that the program make this warning earlies when installing requirements:

Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for ujson<=5.4.0,>=2.0.0 from https://files.pythonhosted.org/packages/fb/94/44fbbb059fe5d295f1f73e731a0b9c2e1b5073c2c6b58bb9c068715e9b72/ujson-5.4.0.tar.gz (from pymilvus==2.2.4->-r .\requirements.txt (line 15)).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.

**Comment by isaaclepes** [comment]
The version of PyMilvus is out of date and trying to use a legacy version of grpcio. I solved this by adjusting the package requirements.  So far, I haven't had an issue with it, but I also don't use Milvus.



Here's what worked for me:

edit requirements.txt
```
beautifulsoup4
colorama==0.4.6
openai==0.27.2
playsound==1.2.2
python-dotenv==1.0.0
pyyaml==6.0
readability-lxml==0.8.1
requests
tiktoken==0.3.3
gTTS==2.3.1
docker
duckduckgo-search
google-api-python-client
pinecone-client==2.2.1
pymilvus
redis
orjson
Pillow
selenium
webdriver-manager
coverage
flake8
sentence_transformers
numpy
pre-commit
black
sourcery
isort
gitpython==3.1.31
grpcio==1.53.0
```
execute:
pip install -r requirements.txt

This fixes the dependency, but there are still errors in the current codebase that will cause it to crash out with stack trace.

**Comment by yusipeng** [comment]
same failure
i have install vs build tools,and add to PATH

Building wheels for collected packages: mmh3
  Building wheel for mmh3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'mmh3' extension
      creating build
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Program Files\Python-3.10\include -IC:\Program Files\Python-3.10\Include /EHsc /TpMurmurHash3.cpp /Fobuild\temp.win-amd64-3.10\Release\MurmurHash3.obj
      error: command 'cl.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmh3
  Running setup.py clean for mmh3
Failed to build mmh3
WARNING: Ignoring invalid distribution -illow (c:\users\yusip\appdata\roaming\python\python310\site-packages)
Installing collected packages: mmh3, distlib, wsproto, ujson, tomli, protobuf, platformdirs, pathspec, packaging, outcome, nodeenv, mypy-extensions, isort, identify, grpcio, exceptiongroup, cfgv, async-generator, webdriver-manager, virtualenv, trio, grpcio-tools, black, trio-websocket, pymilvus, pre-commit, selenium
  Running setup.py install for mmh3 ... error
  error: subprocess-exited-with-error

  × Running setup.py install for mmh3 did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running install
      running build
      running build_ext
      building 'mmh3' extension
      creating build
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Program Files\Python-3.10\include -IC:\Program Files\Python-3.10\Include /EHsc /TpMurmurHash3.cpp /Fobuild\temp.win-amd64-3.10\Release\MurmurHash3.obj
      error: command 'cl.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> mmh3

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by synxero354** [comment]
> The version of PyMilvus is out of date and trying to use a legacy version of grpcio. I solved this by adjusting the package requirements. So far, I haven't had an issue with it, but I also don't use Milvus.
> 
> Here's what worked for me:
> 
> edit requirements.txt
> 
> ```
> beautifulsoup4
> colorama==0.4.6
> openai==0.27.2
> playsound==1.2.2
> python-dotenv==1.0.0
> pyyaml==6.0
> readability-lxml==0.8.1
> requests
> tiktoken==0.3.3
> gTTS==2.3.1
> docker
> duckduckgo-search
> google-api-python-client
> pinecone-client==2.2.1
> pymilvus
> redis
> orjson
> Pillow
> selenium
> webdriver-manager
> coverage
> flake8
> sentence_transformers
> numpy
> pre-commit
> black
> sourcery
> isort
> gitpython==3.1.31
> grpcio==1.53.0
> ```
> 
> execute: pip install -r requirements.txt
> 
> This fixes the dependency, but there are still errors in the current codebase that will cause it to crash out with stack trace.

you can probably resolve those issues by updating pymilvus to 2.2.6

**Comment by adivinsky** [comment]
> > The version of PyMilvus is out of date and trying to use a legacy version of grpcio. I solved this by adjusting the package requirements. So far, I haven't had an issue with it, but I also don't use Milvus.
> > Here's what worked for me:
> > edit requirements.txt
> > ```
> > beautifulsoup4
> > colorama==0.4.6
> > openai==0.27.2
> > playsound==1.2.2
> > python-dotenv==1.0.0
> > pyyaml==6.0
> > readability-lxml==0.8.1
> > requests
> > tiktoken==0.3.3
> > gTTS==2.3.1
> > docker
> > duckduckgo-search
> > google-api-python-client
> > pinecone-client==2.2.1
> > pymilvus
> > redis
> > orjson
> > Pillow
> > selenium
> > webdriver-manager
> > coverage
> > flake8
> > sentence_transformers
> > numpy
> > pre-commit
> > black
> > sourcery
> > isort
> > gitpython==3.1.31
> > grpcio==1.53.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > execute: pip install -r requirements.txt
> > This fixes the dependency, but there are still errors in the current codebase that will cause it to crash out with stack trace.
> 
> you can probably resolve those issues by updating pymilvus to 2.2.6

I upgraded pymilvus (via pip install --upgrade pymilvus) and this didn't resolve the issue.
![2023-04-15_15h33_28](https://user-images.githubusercontent.com/4327021/232249901-eee11073-233f-4252-9186-bb17a7a16047.png)

**Comment by chyezh** [comment]
it seems a python environment problem.
I have solved these problem by using venv to create a clean python virtual environment.

**Comment by Pwuts** [comment]
Is this still an issue with the latest `master`? If so, please let me know what platform you are on.

**Comment by Pwuts** [comment]
Closing as resolved. Feel free to reopen if not, but test first with `master`.

**Comment by ThanhLV97** [comment]
Please change to the latest version. At this time, I changed my requirements just like:
`grpcio==1.59.3
grpcio-tools==1.59.3`
