### ISSUE TITLE
Update installation instructions to automatically clone the stable branch

### ISSUE THREAD

**Issue by itsmarble** [Significant-Gravitas/Auto-GPT#1661]
### Summary 💡

I suggest updating the installation instructions in the README to automatically clone the stable branch, ensuring users get the latest stable release by default.

### Examples 🌈

The current instructions for cloning the repository are as follows:

```
git clone https://github.com/Torantulino/Auto-GPT.git
```

I propose updating the instructions to clone the stable branch by default:

```
git clone --branch stable https://github.com/Torantulino/Auto-GPT.git
```

This way, users will always be on the stable branch, reducing the chances of encountering issues related to the master branch's potentially broken state.

### Motivation 🔦

This change will make it easier for users to get started with Auto-GPT by ensuring they are on the stable branch, which should be more reliable than the master branch. It will also minimize the need for troubleshooting, as users will be less likely to face issues arising from a broken master branch.

**Comment by tomrhudson** [comment]
This seems to be resolved, _docs/installation_ reads correctly. Could update the README URL to state refer to https://github.com/Significant-Gravitas/Auto-GPT/tree/stable instead of using the link that is currently there which is https://github.com/Significant-Gravitas/Auto-GPT/releases/latest; is that required?
