### ISSUE TITLE
Even when using --gpt3only, the evaluate_code function still tries to use gpt-4

### ISSUE THREAD

**Issue by rogeriosmorais** [Significant-Gravitas/Auto-GPT#168]
See screenshot below. Also, it doesnt show in the image, but at the start of the execution it confirmed GPT3.5 Only Mode - ENABLED

![image](https://user-images.githubusercontent.com/28842513/229779684-42cecf1e-c1e6-4b35-9c5e-68d23a13bc40.png)

**Comment by cryptidv** [comment]
This should be fixed. Looking through the code the `analyze_code` method utilizes the smart model found at `Config#smart_llm_model`, which is set to the fast model if `--gpt3only`. 

Might re-evaluate how we handle `--gpt3only` and `--gpt4only` because the current logic doesn't really match what these 2 flags are supposed to do.

Either way closing as solved.
