### ISSUE TITLE
Invalid syntax with python 3.11.3

### ISSUE THREAD

**Issue by nreck** [Significant-Gravitas/Auto-GPT#1832]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Install Python 3.11.3 through Homebrew
Follow AutoGPT install instructions: https://autogpt.net/autogpt-installation-and-features/
Run python scripts/main.py

### Current behavior 😯

I get the error:
>>> python scripts/main.py
  File "<stdin>", line 1
    python scripts/main.py
           ^^^^^^^
SyntaxError: invalid syntax

### Expected behavior 🤔

Run

### Your prompt 📝

```yaml
Run python scripts/main.py
```

**Comment by stephane303** [comment]
it runs fine on my windows machine with 3.11.3 on the stable branch

**Comment by hemangjoshi37a** [comment]
Hi @nreck, 

The error "SyntaxError: invalid syntax" occurs when there is a syntax mistake in the code. In your case, it seems that you are trying to run the command "python scripts/main.py" in the Python interpreter instead of the command line interface.

You need to open the command prompt or terminal and navigate to the directory where the "main.py" file is located. Then run the command "python main.py" to execute the script.

I hope this helps. Let me know if you have any further queries.

**Comment by ngmisl** [comment]
Use 3.10 instead, I have had no success with 3.11

**Comment by p92** [comment]
beware on some systems you have to use  python3  and not python command to use correct version of python.

**Comment by therzv** [comment]
it works well on python 3.10, so you must check your python version.
i have many python version on my mac. and the default when i type ```python``` is going to python version 2.7

this is on my local mac.
<img width="1076" alt="Screen Shot 2023-04-26 at 08 07 04" src="https://user-images.githubusercontent.com/30797808/234434009-5401fc54-9b8d-4847-83b0-686185ca04c4.png">

To solve above issue, i change python inside the run.sh to python3.10 like this : 

```
#!/bin/bash
python scripts/check_requirements.py requirements.txt
if [ $? -eq 1 ]
then
    echo Installing missing packages...
    pip3.10 install -r requirements.txt
fi
python3.10 -m autogpt $@
read -p "Press any key to continue..."
```

and it works well

**Comment by hemangjoshi37a** [comment]
@therzv  congratulations :+1:

**Comment by Pwuts** [comment]
`scripts/main.py` doesn't exist anymore. Check the documentation for instructions on how to run Auto-GPT.
