### ISSUE TITLE
How to use AutoGPT with login-only websites?

### ISSUE THREAD

**Issue by jsmith-dev** [Significant-Gravitas/Auto-GPT#1948]
### Discussed in https://github.com/Significant-Gravitas/Auto-GPT/discussions/918

<div type='discussions-op-text'>

<sup>Originally posted by **meadow-kun** April 12, 2023</sup>
For a particular pipeline I would like to use my personal LinkedIn account. It's not for stupid crazy scraping or so, just automating a task which is typically automated by other plugins. How can I setup and instruct AutoGPT to make use of this data source? </div>

**Comment by jsmith-dev** [comment]
Working on this.

**Comment by bjornfix** [comment]
Yeah. Same issue here. I would not mind giving it access to our Google Workspace E-mail system as well, so it can help out replying to emails. Also, we use it for logins to social media accounts everywhere.

**Comment by atreiou** [comment]
Definitely following for control of my LinkedIn

**Comment by hedonnn** [comment]
Interested!

**Comment by Bioblaze** [comment]
I wrote code for handling google workspace email accounts

**Comment by bjornfix** [comment]
Fantastic!

**Comment by jacksonblankenship** [comment]
Since I'm already logged into all my accounts on my local Chrome profile, I added this line to `web_selenium.py` (lines 71-73) so it can use my logins. I believe this would solve this issue for most people.

If you need to know where your profile is, go to `chrome://version` in Google Chrome and copy the path for `Profile Path`.

<img width="1007" alt="Screenshot 2023-04-18 at 8 05 04 PM" src="https://user-images.githubusercontent.com/26150050/232940009-b252c7ce-d3d6-4e33-9a8f-97bc06eaf3da.png">

**Comment by mathematicsofpaul** [comment]
Could you elaborate what you mean by local Chrome profile? I've been trying to figure out how to get auto-gpt to launch the webscrapping process with my already logged in google profile a.k.a my google account, but for some reason it is simply just launching with a 'clean slate' browser instead. 

![Screen Shot 2023-04-20 at 11 24 06 pm](https://user-images.githubusercontent.com/31915369/233380568-84146ae3-3eff-425f-bb56-7abf988887ed.png) 

I want to launch with my own already logged in google profile because it has all my need logins for the webscrapper to use. 

![Screen Shot 2023-04-20 at 11 26 52 pm](https://user-images.githubusercontent.com/31915369/233381371-091b0b71-753b-49be-8640-03476c02ae58.png)

The change above is definitely not working for me (well at least for my needs).

**Comment by ntindle** [comment]
Would love to see some of these comments in a plugin

**Comment by mathematicsofpaul** [comment]
@jacksonblankenship Would you have any input on this matter? :)

**Comment by steelliberty** [comment]
I need the same thing. I have seen autogpt open chrome and read data using selenium. filling two fields and clicking submit button should be easy. Is there anyway to have the agent execute code as part of a goal?

**Comment by adamtaheri** [comment]
Following. This sounds super easy; why can't the AI execute some selenium code? @jacksonblankenship I tried your solution but it didn't seem to work

**Comment by jacksonblankenship** [comment]
> Following. This sounds super easy; why can't the AI execute some selenium code? @jacksonblankenship I tried your solution but it didn't seem to work

It was working fine for me a week or two. Assuming some additional conflicting args are being passed now or something. I may be able to take a look later.

**Comment by adamtaheri** [comment]
Please let me know when you can, appreciate it!

**Comment by mathematicsofpaul** [comment]
Thanks @jacksonblankenship . Could you elaborate where to look in order for us to fix the issue? I'm really new to Selenium and not sure where to start.

**Comment by jacksonblankenship** [comment]
> Thanks @jacksonblankenship . Could you elaborate where to look in order for us to fix the issue? I'm really new to Selenium and not sure where to start. 
> 
> 
> 
> If you know what version of Autogpt you used that would be great too!

I'm not very experienced in Python/Selenium, but I have used Node with Puppeteer and Playwright a lot. At the end of the day, Selenium, Puppeteer and Playwright are abstraction layers that make it easy to interface with Chromium.

https://www.chromium.org/chromium-projects/

This project happens to use Selenium, but don't focus too hard on that part. Understand that the end goal is to pass the correct arguments to the browser (i.e. Chromium).

**Comment by adamtaheri** [comment]
I’m on the latest version of that helps.
