### ISSUE TITLE
general feedback and issues

### ISSUE THREAD

**Issue by torchesburn** [Significant-Gravitas/Auto-GPT#2036]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

generally when you allow local commands in .env, the AI does not recognise where the "cursor" is in terms of the directory, so it can go ahead and make a bunch of directories and files, but always reverts to the root directory, "auto_gpt_workspace".

it loses its place, doesnt really remember structure either

**Comment by Qoyyuum** [comment]
Hi @torchesburn are you saying that the AI just creates new files and folders in `auto_gpt_workspace` folder and nowhere else? If so, that is by design.

See here: https://github.com/Significant-Gravitas/Auto-GPT/pull/2512 and https://github.com/Significant-Gravitas/Auto-GPT/issues/666

If its not that, can you clarify what the issue is?

**Comment by torchesburn** [comment]
Sometimes it defaults to my root directory instead of the workspace, and then goes back to the workspace and corrects itself.


Seems to be working correctly as of master and latest stable, I've not had this issue since.
