### ISSUE TITLE
can't use files in the workspace

### ISSUE THREAD

**Issue by 3DAuckland** [Significant-Gravitas/Auto-GPT#2079]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

its trying to use read file

each time gets this error

SYSTEM:  Command read_file returned: Error: 'WindowsPath' object has no attribute 'is_relative_to'

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Panosensing** [comment]
same here , don't know what to do next

**Comment by XFFXFF** [comment]
@3DAuckland @Panosensing   I encountered the same issue and discovered that it was caused by the version of Python I was using. Currently, I am using Python 3.8, but it turns out that [`is_relative_to`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.is_relative_to) was introduced in Python 3.9.

![image](https://user-images.githubusercontent.com/30254428/232408726-cab12e27-ce52-427a-b136-988653e7f680.png)

**Comment by 3DAuckland** [comment]
Thanks @XFFXFF ! Will update python

**Comment by ntindle** [comment]
Fixed?
