### ISSUE TITLE
Add support for termux, not root, in armv7l architecture which is the general one used nowadays.

### ISSUE THREAD

**Issue by Darkrevengehack** [Significant-Gravitas/Auto-GPT#2350]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

It has to work based on knowledge of what you are talking about, that is, if you tell him something and then you tell him something of what you already said, it has to work like that, as I say it to have Good performance on termux, Linux and Kali Linux, especially termux without root.

### Examples 🌈

Termux, Kali Linux and linux

### Motivation 🔦

Chatgpt 4 and autogpt4

**Comment by ntindle** [comment]
I am almost certain this won't be possible for a reasonable amount of time due to the dependencies required

**Comment by sudomain** [comment]
Actually I had v0.2.1 working in Termux, though I had to remove "sourcery" from requirements.txt. I didn't do extensive testing, but they have a packaged version of firefox now so that should work.

Unfortunately, I just upgraded to v0.2.2 and now pip gives errors about not being able to install a new module named "spacy". It's something I have to work out

**Comment by nanis94** [comment]
thank you really :)

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: sudomain ***@***.***>
Gönderildi: Saturday, April 22, 2023 10:54:56 PM
Kime: Significant-Gravitas/Auto-GPT ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: Re: [Significant-Gravitas/Auto-GPT] Add support for termux, not root, in armv7l architecture which is the general one used nowadays. (Issue #2350)


Actually I had v0.2.1 working in Termux, though I had to remove "sourcery" from requirements.txt. I didn't do extensive testing, but they have a packaged version of firefox now so that should work.

Unfortunately, I just upgraded to v0.2.2 and now pip gives errors about not being able to install a new module named "spacy". It's something I have to work out
