### ISSUE TITLE
reward system for autogpt

### ISSUE THREAD

**Issue by horazius** [Significant-Gravitas/Auto-GPT#2446]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Introduce a reward system so that AutoGPT can also learn. You should be able to see all actions in a history. Possibly even be able to call up parameters and then evaluate them with positive "p" and "n" negative. This evaluation file could then be shared as an extension among different users or in the end even played back to openAi for learning.

### Motivation 🔦

To improve the software by crowd learning. The basics of ChatGPT

**Comment by Androbin** [comment]
Please note that GPT-4 can only do in-context learning, as the API does not currently support fine-tuning the model.

**Comment by Boostrix** [comment]
this is more important than people may think, you need this for any sort of fitness function / training purposes - regardless of whether the LLM supports this or not, the reward system could also be executed locally to self-optimize.

And all actions/commands have a certain cost associated with it.
So in general, all actions/commands need to expose their costs so that a local reward function can optimize for those.
