### ISSUE TITLE
Command browse_website Error

### ISSUE THREAD

**Issue by Jbbancud10** [Significant-Gravitas/Auto-GPT#2468]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Other (Please specify in your problem)

### GPT-3 or GPT-4?

GPT-3.5

### Current behavior 😯

Error: [Errno 8] Exec format error: '/data/data/com.termux/files/home/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver'

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Notarin** [comment]
Hi! Your issue is missing many details, for example, you've set your operating system to other, but have not specified what it is in your problem (I have a suspicion it is Android), also, you've not provided your prompts nor your logs. If you could edit your issue to include these details it would be a massive help to determine the cause of your issue.
However, with what details I have available at the moment, I think the most likely issue is to do with technical issues regarding Termux and the ChromeDriver executable. 

@Jbbancud10 Have you made any changes to your termux environment that we would have to make as well in order to reproduce your issue?

**Comment by brunobulox** [comment]
I am getting the same error, SYSTEM:  Command browse_website returned: Error: [Errno 8] Exec format error: '/app/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver' from the ceramicwhite/auto-gpt:latest image from Dockerhub as well as "SYSTEM:  Command browse_website returned: Error: [Errno 8] Exec format error: '/home/pi/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver'"  from a local instance of Auto-GPT-0.2.1. Both of them running on a Raspberry Pi 4. Nothing juicy gets written to the local logs. Whatever additional data you need I can provide
