### ISSUE TITLE
SYSTEM:  Command google returned: Error: EOF occurred in violation of protocol (_ssl.c:997)

### ISSUE THREAD

**Issue by sxzq46** [Significant-Gravitas/Auto-GPT#2484]
NEXT ACTION:  COMMAND = google ARGUMENTS = {'input': 'chatGPT principles and applications'}

**Comment by Notarin** [comment]
Hi! your issue is lacking a severe amount of details, please if possible follow or use the templates provided for making issues, they're presented to you when pressing the 'new issue' button.
![image](https://user-images.githubusercontent.com/25104390/232976436-f02b1bf1-d83b-4564-b686-743231b9e108.png)
Which results in this page
![image](https://user-images.githubusercontent.com/25104390/232976493-c054a873-bb30-41fa-b9c3-8d6ba7052c1d.png)
And in this case you would select 'Bug Report' resulting in the following page.
![image](https://user-images.githubusercontent.com/25104390/232976646-eac6a10f-e21f-479b-a707-da5c5d95be79.png)
You would then fill out the details and submit, thus properly ensuring that all relevant details are included.
