### ISSUE TITLE
same webpage analyzed more and more times

### ISSUE THREAD

**Issue by SpaceTTAngel** [Significant-Gravitas/Auto-GPT#2692]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

During the research on google, AutoGpt analyze the same webpage several times.
It seems that no memory of the web page analyzed is present.

### Expected behavior 🤔

Should be natural that the same webpage must be analyzed on time, not several times

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by SpaceTTAngel** [comment]
Auto-GPT is also not able at the moment to use several pages of google search, but uses always the first websites found in the browers; it seems is not able to change pages 1,2,3,4 of a google websites.

Moreover the fact that analyze the same webpage is a blocking problem in my opinion

**Comment by savethehousemouse** [comment]
I tried to 'help' it in those 5 steps available I wrote:

1) collect from at least 5 different **unique** scholarly sources arguments for and against the xxxx theory **and use a log of the visited source** so that each source is only processed once.

2) evaluate the plausibility and weight of each argument

3) compare the arguments pro against the contra argument and their weights and build a table for both

4) show the table in the browser as an html page

Maybe there is a better way to help eliminate recursions. There appear backlinks all over and that results in said loops. 
It never finishes. 
It is not uncommon that references from different article point to the same source in their references.

**Comment by yasiu071** [comment]
Yeah, my research is growing very slow, because AGTP is working on same pages over and over. Only thing that changes is wording of summaries sometimes. I asked it to keep list of sites not giving any new insight, but it's not helping :( It's worse as most of visited pages in my research are broken links.

**Comment by ntindle** [comment]
Sometimes it executes something unexpected or doesn’t do what you want.  Check out the #prompt-engineering channel in discord to get a better fit prompt

**Comment by savethehousemouse** [comment]
i don't understand. It's closed now. What is the solution or what is the workaround? any decent academic or nonacademic paper has references, footnotes and if the subject interested many researchers, they will backreference each other. This is not a once in a lifetime, special situation but one that many researchers have and will constantly be confronted with.

**Comment by SpaceTTAngel** [comment]
I suggest to take opened this topic, not to close @ntindle , ok?
