### ISSUE TITLE
Add callout to use Python v3 in README

### ISSUE THREAD

**Issue by dtbuchholz** [Significant-Gravitas/Auto-GPT#2825]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

When initially configuring AutoGPT, you must run `./run.sh`. If you're using Python v2, it's possible that you'll run into a build error; this does not occur with v3. Particularly, this might happen on Macs.

One solution is described on [StackOverflow](https://stackoverflow.com/a/49711594), which describes updating your bash/zsh rc `PATH` to point to the location of v3 (e.g., `export PATH=/usr/local/opt/python/libexec/bin:$PATH`).

### Examples 🌈

If using Python v2, you might see the following error upon running `./run.sh`:
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dtb/ai/autogpt/autogpt/__main__.py", line 2, in <module>
    import autogpt.cli
  File "autogpt/cli.py", line 52
    ctx: click.Context,
       ^
SyntaxError: invalid syntax
```

### Motivation 🔦

Improve the onboarding process for AutoGPT 🙌 .

**Comment by k-boikov** [comment]
Python 2 is totally unsupported by AutoGPT.

**Comment by frankbecker** [comment]
Thanks for sharing this. I had the same issue, since my Mac came or had Python 2.7 installed at some point, and it created all sorts of issues for me. It kept colliding with Python 3

**Comment by dtbuchholz** [comment]
Forsure! I think I might have been a bit misleading in my issue @k-boikov, and it'd still be helpful to just make this callout somewhere. 

Namely, I know the README states v2 isn't supported, but for those who don't use python often, this config callout can help save them time or even prevent them from giving up entirely. It could be a brief footnote bullet.

**Comment by haithamelmengad** [comment]
Running into the same issue even after setting Python 3 as the default, it keeps colliding with python 2

**Comment by dtbuchholz** [comment]
@haithamelmengad what's your OS (Mac M1/silicon or intel, etc.) and what's the full logged message (even before that specific error line)?

**Comment by haithamelmengad** [comment]
Thanks for the quick response. I went around this issue by running `python -m autogpt` instead of `./run.sh start` in a terminal. There's at least one other issue thread mentioning python version colliding as a blocker for the latter command, so perhaps the guide can suggest this as an alternative.

Here's the info you requested:

Full logged error message
<img width="1034" alt="Screen Shot 2023-04-25 at 2 10 14 AM" src="https://user-images.githubusercontent.com/23226879/234150416-8d2f2863-cb4e-4069-ad27-505b3341be31.png">

Log after `brew info python`
<img width="701" alt="Screen Shot 2023-04-25 at 2 12 24 AM" src="https://user-images.githubusercontent.com/23226879/234150630-122bcb51-2233-424c-87ef-4d5715fe72c0.png">
