### ISSUE TITLE
全中文autogpt教程

### ISSUE THREAD

**Issue by zizhan666** [Significant-Gravitas/Auto-GPT#3021]
### Duplicates

- [X] I have searched the existing issues

### Examples 🌈

![image](https://user-images.githubusercontent.com/76548951/233846217-be579b15-a194-49de-92cb-306f3cc846a0.png)

**Comment by zizhan666** [comment]
![75d2ffaaa5e5c395f3b3878956c005a](https://user-images.githubusercontent.com/76548951/233846236-8e4caddd-a4f4-4a24-a3a2-d5674d62fcc6.jpg)

**Comment by zizhan666** [comment]
欢迎进群讨论

**Comment by ttimasdf** [comment]
@k-boikov This issue is opened by a spammer who opened [multiple issues](https://github.com/Significant-Gravitas/Auto-GPT/issues?q=is%3Aissue+author%3Azizhan666) to promote his paid service. The content he posted (which is a QR code for a Weixin Group Chat) is not useful for this project in any way. I recommend blocking this user.
