### ISSUE TITLE
[Comment] Overwhelmed by your work - underwhelmed by GPT

### ISSUE THREAD

**Issue by Network-Sec** [Significant-Gravitas/Auto-GPT#3103]
I've watched the development of this and don't wanna bore you: This community work is brilliant.

Yet when I see GPT running in circles trying to clone one git repo over and over again, deleting it again, trying to execute it's own .py files using docker (it obviously doesn't have access) and whatnot, while my API bill gets bigger.... :D 

Not that I would want to miss this experiement but am I doing something wrong?

**Comment by CelestialRealmStudios** [comment]
I'm having a similar issue with my autogpt, it tries to do same things over and over and it doesn't notice that it's failed like.. 30 times already so it should change something but it doesn't it just gets stuck in a loop, this happened so many times I gave up, sometimes it won't listen to my instructions despite providing it with feed back, to be honest, I was really looking forward to experimenting with it more but so far it's not been that great, besides I noticed sometimes it doesn't record the values it "Thinks" it has, and it inputs something like "<Search result value>" or "<git hub repository link>" instead of actually executing a command with the proper value in it.

I'd like to know too if I'm doing something wrong lol.

**Comment by OmriSoudry** [comment]
I agree, very difficult to even reproduce the demo examples, using exactly the same prompts... Maybe we're missing something?

**Comment by ntindle** [comment]
Thanks for the support! We’re actively working on methods to make it better via plugins, swapping the LLMs out, making it better at managing agents, improving context appropriate memory, and more! 

I’m going to close this issue so it doesn’t clog the tracker up but if you want to help out with any of the above, join the discord and drop a message in the matching channel!

**Comment by ntindle** [comment]
Also for the demo, it’s running gpt4 which helps a lot
