### ISSUE TITLE
Add dir with interesting "ai_settings"/prompts

### ISSUE THREAD

**Issue by gannonh** [Significant-Gravitas/Auto-GPT#316]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Idea:

- Add a `ai_settings` directory to contain yaml files in the form of `last_run_ai_settings.yaml`. This way we could create and share interesting or successful "missions." 
- Update `scripts/main/parse_arguments` so you can easily load any of the `...ai_settings.yaml` files in the `ai_settings` directory.

Planning to add this to my local fork. Happy to do a PR if others like the idea :)

ps - awesome tool! thanks for sharing with the community!

**Comment by dwrtz** [comment]
I think this is a great idea.

Regarding your second point there have already been multiple requests for this:
- https://github.com/Torantulino/Auto-GPT/pull/257#issuecomment-1497959394
- https://github.com/Torantulino/Auto-GPT/pull/257#issuecomment-1498239993

There's also a bug in determining where to save ai_settings.yaml #318 

I think we need @Torantulino to weigh in on the desired functionality. Here's my proposal:
- [ ] Auto-GPT always saves the last setting it used to ai_settings.yaml.
- [ ] by default, Auto-GPT tries to load ai_settings.yaml and prompts the user if they want to use this setting again (this is the current behavior).
- [ ] An optional flag, e.g. --load_settings=./path/to/settings.yaml and Auto-GPT will try to load the specified file instead of ai_settings.yaml. A couple questions:
  - Since the user explicitly specified the file, should we skip asking the user for confirmation of the settings?
  - If the specified file can't be found, should we fall back to asking the user to enter the settings manually or simply error out?

**Comment by gannonh** [comment]
I've got a pretty decent solution for this on my fork. https://github.com/gannonh/Auto-GPT

- Always saves settings to a unique file in a` history` directory
- Gives you the option at launch to ...
```bash
a - Load last used settings
b - Load another settings file
c - Create new settings
```
All options ask you to confirm your choice. Option b lets you select any file in the history `dir.` Happy to do a PR if there is interest. Thanks!

**Comment by gannonh** [comment]
Screen recording of the feature.

 [New Recording - 4/7/2023, 7:34:43 PM](https://vimeo.com/815785569/2109884fec)

**Comment by gannonh** [comment]
Went ahead and did a PR for this if interested: https://github.com/Torantulino/Auto-GPT/pull/453

**Comment by Boostrix** [comment]
This is kinda overlapping with the idea to come up with actual benchmarks for the project, including whole ai_settings.yaml files that may live inside the repository, also to be used for regression testing purposes: #1359

**Comment by lc0rp** [comment]
FYI - implemented in Turbo: https://github.com/lc0rp/Auto-GPT-Turbo @gannonh, @dwrtz as personas / presets
