### ISSUE TITLE
ISSUE WHEN REOPENING AUTOGPT ON MAC

### ISSUE THREAD

**Issue by xNicky2k** [Significant-Gravitas/Auto-GPT#3366]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

?

### Current behavior 😯

auto gpt won't run 

### Expected behavior 🤔

auto gpt should run

### Your prompt 📝

```yaml
traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/nickboutilier/Auto-GPT/autogpt/__init__.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

### Your Logs 📒

```log
permission denied
```

**Comment by 958121312** [comment]
This is most likely due to the fact that you have multiple versions of python on your machine, so the packages that pip installs are not in the same environment as the python commands you are running, You can check the pip version and python version on your computer, and maybe you should use the `which python` command to see what version is on your computer.

**Comment by 958121312** [comment]
> This is most likely due to the fact that you have multiple versions of python on your machine, so the packages that pip installs are not in the same environment as the python commands you are running, You can check the pip version and python version on your computer, and maybe you should use the `which python` command to see what version is on your computer.

当然，前提是你确保你安装了`python-dotenv`

**Comment by 958121312** [comment]
This is most likely due to the fact that you have multiple versions of python on your machine, so the packages that pip installs are not in the same environment as the python commands you are running, You can check the pip version and python version on your computer, and maybe you should use the which python command to see what version is on your computer.
That's if you have python-dotenv installed

**Comment by 958121312** [comment]
This is most likely due to the fact that you have multiple versions of python on your machine, so the packages that pip installs are not in the same environment as the python commands you are running, You can check the pip version and python version on your computer, and maybe you should use the `which python` command to see what version is on your computer.
That's if you have `python-dotenv` installed

**Comment by braytonstafford** [comment]
My version of pip was not the same version of python so in my conda environment I ran:

`python pip install -r requirements.txt`

This installed the requirements I needed and then running this started auto-gpt successfully

`python -m autogpt`

**Comment by p-i-** [comment]
Closing this as no response from OP, and installation generally works on macOS
