### ISSUE TITLE
One more long term memory layer

### ISSUE THREAD

**Issue by asai95** [Significant-Gravitas/Auto-GPT#3382]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Hey everyone!

I would like to discuss an idea that I have related to a long term memory.

As of now with each run the memory resets, which makes it hard to ingest some hand-picked useful information to an agent. You have to do it each run.
On the other hand, if we just skip the memory reset, it will bloat really fast, considering that an agent can make mistakes, take false assumptions, etc.

So my idea here is to add one more memory index, that will persist between runs, and will be read-only for an agent.
This way we will be able to keep the data that we want to ingest to each run, without littering it with possibly useless information.

### Examples 🌈

For example you may want to feed an agent with some documentation about specific service (like API specs) ask it to write a client library in various languages.
For each language it will search for various info like syntax, packaging, etc, but the API specs will remain the same each time.
So you want to keep the API specs, but do not want to mix packaging in Python and packaging in Go.
With the current implementation you will have to ingest the API specs each run for each language, which will be a waste of resources and time.

### Motivation 🔦

I would like to hear what the community thinks about this?

If the idea makes sense, I can make a PR.

**Comment by ScottSwain** [comment]
YES! This is something I want very badly.
IF I understand you correctly.
Here's my question that may relate. I'm getting no responses so I wonder if I worded it correctly?
I MAY have not made it clear enough that I want to have it "learn" only once but prompt it with many questions once it has the knowledge and rules I want it to follow:
https://github.com/Significant-Gravitas/Auto-GPT/discussions/3585

**Comment by Boostrix** [comment]
> If the idea makes sense, I can make a PR.

I would be interested in seeing such a PR personally - if only to see how you are going to tackle that. I ran into the same restriction, and would basically like to be able to suspend/resume a sub-agent or terminate/restart a fresh agent on demand, and would also need a way to "prime" it accordingly, i.e. without losing some of the information that was previously considered useful - i.e. by the previous agent's invocation. I was thinking of using a separate yaml file - as long as agent's only invoke sub-agents, there would always be a corresponding yaml file to have some intermediate state (even though that would be more in terms of instructions rather than actual intermediate state).

I basically ran into this issue whenever I came up with an agent that only succeeded partially: it would leave a workspace that would hardly be compatible with the way the original ai_settings.yaml file wanted things done. And obviously, re-running the whole agent from scratch can be potentially wasteful.

For instance, when my goals read "create folder foo and create file foo.cc" I needed to adapt the goals to reflect "if necessary" or "if it does not exist already", or "check first ..."
This is kinda redundant and fragile.
It might be better to use the LLM itself to come up with a test for a goal first, and execute that prior to executing the goal.

For example: "Create folder foo"
Would create a test "check if folder foo exists, skip this goal if it exists"

Or: Create file foo/foo.c
Woud create: Check if file foo/foo.c exists, if it does - skipp this part of the goal

Behind the scenes, each goal would need to be split into instruction/sub-goals  which woudl then be mapped to unit tests, which would in turn always be executed prior to executing the actual instruction - that way, we could at least retain /some/ intermediate state in between successive invocations of an agent that may have terminated/cancelled its operation previously.

Now, obviously this would cause more traffic initially, but there's a breakeven point, when using such a mapping between unit_tests[INSTRUCTION] = TEST, would prevent the LLM from being invoked unnecessarily, as it would boild down to a simple memoization/caching scheme.

That's basically how I was thinking about the scheme, inspired by having to edit/restart the same ai_settings.yaml agent over and over again, always faced with different progression states of the underlying workspace directory - and it would be a pity to always discard everything, or see all intermediate state being ignored and redone ...

What do you folks think ?

 
Background / food for thought (seem, we need a meta issue for ideas related to suspending/resuming):
- https://github.com/Significant-Gravitas/Auto-GPT/issues/822
- https://github.com/Significant-Gravitas/Auto-GPT/issues/430
- https://github.com/Significant-Gravitas/Auto-GPT/issues/1531
- https://github.com/Significant-Gravitas/Auto-GPT/issues/1176
