### ISSUE TITLE
Theres no meta data in the memories

### ISSUE THREAD

**Issue by philliplastcall** [Significant-Gravitas/Auto-GPT#3451]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

def add(self, data):
        vector = get_ada_embedding(data)
       ###  # no metadata here. We may wish to change that long term.
        self.index.upsert([(str(self.vec_num), vector, {"raw_text": data})])
        _text = f"Inserting data into memory at index: {self.vec_num}:\n data: {data}"
        self.vec_num += 1
        return _text

### Current behavior 😯

it gets stuck in loops because it thinks failed repeated attempts are relevant and therefore should be tried again and again

### Expected behavior 🤔

know he difference between good and evil...hell i'd take the difference between pass ad fail

### Your prompt 📝

```yaml
# Paste your prompt here
```
read important_info.txt

### Your Logs 📒

```log
it rolls down alone or in pairs, everyone wants a 
```

**Comment by Boostrix** [comment]
> it gets stuck in loops because it thinks failed repeated attempts are relevant and therefore should be tried again and again
> know he difference between good and evil...hell i'd take the difference between pass ad fail

for that to work, an outer/parent agent would need to be able to look at the objective in question and the state (log file) and output (files) of the sub-agent. I started doing some early experiments related to this: https://github.com/Significant-Gravitas/Auto-GPT/issues/3593#issuecomment-1532870949

The idea here would be split up objectives into "atomic" steps, whose completion status is logged to disk - so that the agent/task manager can observe progress (lack thereof).

I am hoping, that in conjunction with hashing agent state, this could also be used to detect redundant looping, as per: https://github.com/Significant-Gravitas/Auto-GPT/issues/3668
