### ISSUE TITLE
COMMAND = write_to_file fails if file exists

### ISSUE THREAD

**Issue by ram-sh** [Significant-Gravitas/Auto-GPT#3514]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Auto-GPT fails to `write_to_file` if file already exists and returns `Command write_to_file returned: Error: File has already been updated.` and can loop over again and again trying to write to that file

to bypass this behavior, i had to remove the line manually `write: hello.py` from the `file_logger.txt` each loop for Auto-GPT keeps on working on the file.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
THOUGHTS:  I think I will start by writing a file named hello.py and changing its content.
REASONING:  The goal is to write a file named hello.py, so I will use the 'write_to_file' command to create the file and add content to it.
PLAN: 
-  Use the 'write_to_file' command to create a file named hello.py and add content to it.
CRITICISM:  I need to ensure that the file is created successfully and that the content is added correctly.
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'hello.py', 'text': "print('Hello, World!')"}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command write_to_file returned: Error: File has already been updated.
 THOUGHTS:  Since the file already exists, I will use the 'read_file' command to check its content.
REASONING:  The 'read_file' command will allow me to check the content of the file named hello.py and ensure that it contains the correct code.
PLAN: 
-  Use the 'read_file' command to check the content of the file named hello.py.
CRITICISM:  I need to ensure that the file is read successfully and that the content is correct.
NEXT ACTION:  COMMAND = read_file ARGUMENTS = {'file': 'hello.py'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command read_file returned: Hello, world!This is another line of text.
 THOUGHTS:  I will use the 'write_to_file' command again to change the content of the file named hello.py.
REASONING:  The 'write_to_file' command will allow me to change the content of the file named hello.py to the correct code.
PLAN: 
-  Use the 'write_to_file' command to change the content of the file named hello.py to the correct code.
CRITICISM:  I need to ensure that the file is updated successfully and that the content is correct.
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'hello.py', 'text': "print('Hello, World!')\n"}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command write_to_file returned: Error: File has already been updated.
 THOUGHTS:  I will use the 'append_to_file' command to add a new line of text to the file named hello.py.
REASONING:  The 'append_to_file' command will allow me to add a new line of text to the file named hello.py without overwriting the existing content.
PLAN: 
-  Use the 'append_to_file' command to add a new line of text to the file named hello.py.
CRITICISM:  I need to ensure that the file is updated successfully and that the new line of text is added correctly.
NEXT ACTION:  COMMAND = append_to_file ARGUMENTS = {'file': 'hello.py', 'text': 'This is another line of text.\n'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:
```

**Comment by ram-sh** [comment]
to bypass the issue I've commented out the following lines from the function `write_to_file` in `/workspaces/Auto-GPT-0.2.2/autogpt/commands/file_operations.py`:

`# if check_duplicate_operation("write", filename):`
`#     return "Error: File has already been updated."`

**Comment by bobisme** [comment]
I've got a PR open to fix this #3489

**Comment by stephane303** [comment]
If this has been merged to master, the issue is still here
Testing with https://github.com/Significant-Gravitas/Auto-GPT/commit/4767fe63d36e0eece256ddcc2d8dc49812215277, which is the last commit in master at the time of writing

**Comment by bfalans** [comment]
Opened PR #3643 for fixing this issue

**Comment by Boostrix** [comment]
can confirm that I can still reproduce the issue.
Regarding duplicate operation checking: I suppose, IF the file exists, it might make more sense to take a hash and compare its contents with the new contents

**Comment by bobisme** [comment]
@Boostrix so you're talking about a situation where the operation is in the log, but someone has manually deleted it?

**Comment by Boostrix** [comment]
well, not sure if that's generally the case, I believe I was seeing this because I was re-running the same agent (ai_settings.yaml) file giving it variations of the same objectives, so it would obviously have some leftover state (in the form files but apparently also log data?)

Regarding my comment, the idea was not that someone might actually delete the file, but that it may be there and may need to be updated by an agent (because it was created by another run/instance, not sure if that makes sense).

Also, checking for duplicate ops is obviously meaningful, but should probably yield a response that affects the plan/planning process, so that it knows something went haywire. The errors I've been seeing related to this, didn't impress the planner much - it would simply re-loop, not even changing its approach (aka, same command/same params).

This is why I elsewhere suggest to hash action [command] + params and use that as the key into a dict to be able to increment a counter - if that is also done for the response, we can at least use some plausible heuristics to tell if the agent is doing something kinda retarded.

Likewise, the command registry/list offered to the LLM to pick the next step would probably benefit from being augmented with a success/fail history (number of invocations and percentage of successes/fails of a certain command) - that would enable the LLM to quickly notice that something isn't quite right with the provided command (in conjunction with a corresponding constraint/performance evaluation) - as it would enable the LLM to favor actions that worked "recently" (I believe I described that somewhere using the "MRU" acronym)

**Comment by bobisme** [comment]
don't know about all that, but this makes me realize that the file operations log is not a reliable source of truth as it's duplicating the state of the filesystem and it's trivial for those to go out of sync...

**Comment by Boostrix** [comment]
right, you don't need to do anything fancy to make these heuristics go haywire - it's sufficient to resume/re-run an agent or refer to the same file several times via the same list of objectives, sooner or later you'll end up crippling the whole workflow that way. The only way to work around this issue is to intervene and tell the agent to use an alternate solution like a CLI editor
