### ISSUE TITLE
Separation of execution and planning into different agents

### ISSUE THREAD

**Issue by dschonholtz** [Significant-Gravitas/Auto-GPT#3593]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

The core problem here is the plan must be inferred by past work via memories and it is not clear to the user or the agent how much of the plan was actually accomplished by a given command. Ideally, this would be explicit.

So given a task from the user (or a list of goals) The task planner agent will make a list of next tasks to do with their completion status.

Then we will store these tasks in a queue and pop off the first one with all dependencies done and give it to an execution agent.
The execution agent eventually should have a minified task command set for the problem to reduce unnecessary and incorrect commands, but for now, it will just execute with the agent it currently uses in the main execution loop.

Concretely here this is from an architecture perspective. 

The user enters a task they wish the agent to do.

We add a new class called TaskManagerLLM.
As we enter chat.py the objective and current task list if there is one is fed into taskManagerLLM and an empty initial result is fed into it.
Task manager LLM creates up to 7 tasks it should do to accomplish this task. It numbers them with priority and marks dependencies where dependencies are based off of a linked list pointer structure. It also will have the specific command that should be used for each of them. It will not have in it what parameters are to that command though.

It's prompt should be very similar to the existing execution agent with the following components:
Thoughts:
Reasoning:
Task List in JSON
Criticism:
Speak:
Task List JSON.

We then extract that JSON using our existing JSON parsing toolset.
Sort the created tasks without dependencies and then pick the top one. 
Give that task to an execution agent.

An execution agent will function the same way that an existing agent does. It will make a plan for it's very simple  (by comparison task.)
The execution agent will do a one shot evaluation with the "smart" model to generate the given command with the correct params.
To support this, we will first generate relevant context for it by having one more previous command to an LLM that takes in the output from the planning agent, and the goal, and the given task that has been selected and the results from previously completed tasks and have it output a prompt for the agent that succinctly describes the problem the agent is solving by executing that command.

The biggest potential problem with this is having this function with summation based or vectorized based memory.

For now, each completed task would get added to memory with the reasoning associated with it.

It is possible that the above is overly complex, and we just need an ordered task list based on commands in the planning step and its summarization memory. I might implement that first and see how it does.

### Examples 🌈

One example of a specific implementation can be found here: https://github.com/yoheinakajima/babyagi/blob/main/classic/BabyBeeAGI

### Motivation 🔦

We have a lot of performance degradation for a few reasons. Myself, and a few of the other people doing benchmarks have kind of realized that it isn't useful to do benchmarks at this point because they mostly just show how unreliable the agent is. No point in doing token counting for instance if the agent only finishes the simplist tasks 50% of the time.

A lot of the problems with memory and elsewhere is the fact that we have all of this random crap that isn't relevant to the current task and we don't really process well with respect to planning what our next task is, or plan well for next task should be, or really process what our previous tasks accomplished were. And we spend a lot of precious token real estate on stuff that is mostly just confusing to the agent.

The basic thought is, if you have a call to an agent that maintains a list of tasks done, their results and what tasks should be accomplished next, and another separate execution agent, that takes that output and then executes on it for a simple task you should get far better performance. 

Eventually, I would want to make all of the details for each task queryable so that if previous similar tasks have been executed before, we could feed that into the execution agent, but currently I think I want to keep an initial PR simple. 
So my hope is to work on this, and then circle back around and show we can actually finish some benchmarks reliably

**Comment by dschonholtz** [comment]
My plan is to start working on this later tonight and tomorrow. I would like feedback, but let's discuss on discord

**Comment by Garr-tt** [comment]
Feels like this is definitely needed for React Development would love to test if for ya

**Comment by samuelbutler** [comment]
the linked example doesn't have syntax highlighting so here a gist of BabyBeeAGI with syntax highlighting
https://gist.github.com/samuelbutler/deccce61cd825170b3afcc31dd63fbd8

**Comment by Boostrix** [comment]
I have some thoughts related to this and began making early experiments, and got pretty good results, too.

The basic idea is to use aggressively-tuned prompts to make the LLM respond with lists of steps, which are in turn recursively split up and serialized to distinct JSON files to track "progress per step".

In pseudo code terms, the idea is to provide a new command called "plan_task" which takes a <detailed description> of the task, as well as <relevant constraints>

in app.py, I am using start_agent to start a new sub-agent, whose task is to to take the description/constraints of the task and come up with the corresponding list, including an estimate of the complexity (percentage of the whole task).

Up to this point, the LLM is handling all the difficult stuff, so we're talking about 20 lines of code at most.

I am then hashing each step on the list to put that info into a JSON file (to track progress).

For each step, I am also creating a dedicated JSON file that contains the actual task at hand, as well as a status/progress field (to track progress).

The idea being, the "plan_task" command could check for existing JSON files inside the workspace (based on the hash) and use those to continue its work. 

Once all steps are serialized to disk, we can edit all step files that have a difficulty/complexity higher than some threshold of say 20%. This is to "strategize" and come up with alternatives, to have a fallback plan (which would be also passed to the LLM and saved inside the JSON file).

The goal here being to come up with a simple planning framework that is step based, and that can be interrupted/continued, to resume its work later on.

For the time being, I can provide a high level description to create a project with 2-3 files and the planning stage will come up with a list of steps, which can then be sequentially tackled (everything is sequential for now, no parallelism).
The idea is to be able to call a planning/strategy routine that will try different approaches to accomplish a certain task, with the option of suspending/resuming operation.

Ideally, this setup would work for several tasks and could recursively call itself.
At some point, potentially in a concurrent fashion.

One option might be making a dedicated plugin for this, unless this is something that should better be part of the system?
I suppose it would make sense to talk about the various ideas here ...

Any thoughts / ideas ?

**Comment by Boostrix** [comment]
In a sense, a number of seemingly unrelated issues could be unified this way. Because they're all primarily due to a lack of planning and lack of preparing actions before executing them: 

- #503
- #2987
- #1327 
- #3635
- #3444
- #2459
- #3577

**Comment by Garr-tt** [comment]
> In a sense, a number of seemingly unrelated issues could be unified this way.


Yup this is a big one

**Comment by anonhostpi** [comment]
Possibly related rearch work: https://github.com/Significant-Gravitas/Auto-GPT/pull/3790

**Comment by dschonholtz** [comment]
This is great. I am trying to work on challenges/benchmarking so if someone wanted to take a crack at this by all means go for it as I don't think anyone is actively working on the code. My guess is we should hold off until the re-architecturing work is done

**Comment by Boostrix** [comment]
FWIW, when I played with this, I thought that detangling the mess that mutual dependencies in between tasks introduce (and exploring potential concurrency opportunities) woud quickly get haywire - so I tinkered with the idea of using pymake to use the LLM to generate a corresponding Makefile equivalent to be able to continue "building" the plan.

Turns out, that approach can be improved upon, too.
The following is an article about using an LLM to translate a plain text plan into actual markup for a planning framework, and then translating that back to human language again: https://www.marktechpost.com/2023/04/30/this-ai-paper-introduces-llmp-the-first-framework-that-incorporates-the-strengths-of-classical-planners-into-llms/

I haven't looked at existing libs/frameworks available in Python, but this approach sounds rather interesting and like much less work in comparison to reinventing the wheel:

- PANDA: PANDA (Python Algorithm for Navigation and Data-Association) is a Python library for multi-target tracking and planning. It provides a framework for representing objects and their trajectories, as well as algorithms for predicting future trajectories and planning paths to intercept or avoid them.
- PyPlanner: PyPlanner is a Python library for automated planning and scheduling. It provides a way to represent tasks and their dependencies, as well as algorithms for planning and executing tasks. PyPlanner is exclusively written in Python.
- AIMA: AIMA (Artificial Intelligence: A Modern Approach) is a widely used textbook on artificial intelligence that includes Python code examples and implementations of various AI algorithms, including planning algorithms. The book and accompanying code are available online for free.
- PYSAT: PYSAT (Python Satellite Data Analysis Toolkit) is a Python library for working with satellite data. It includes a planning module that provides algorithms for scheduling and optimizing satellite observations.
- PySMT: PySMT is a Python library for working with Satisfiability Modulo Theories (SMT) problems. It includes a planning module that provides algorithms for solving planning problems using SMT solvers.

The point being, with that number of Python based-options, we could just use an adapter/bridge to ask the LLM to translate a set of objectives into a plan for the corresponding planning tool, and then provide 5+ options to evaluate how well these work. Basically, treating the whole thing like a benchmark for now - adding 5+ dependencies in a dev branch should be a no-brainer, and then we'll see which of these is capable of translating most plans into actionable markup.
