### ISSUE TITLE
Issue building Autogpt from docker

### ISSUE THREAD

**Issue by Gnomesong** [Significant-Gravitas/Auto-GPT#4296]
when I enter the command in terminal "docker-compose up --build auto-gpt, I end up getting the following error message

#0 40.86 Traceback (most recent call last):
#0 40.86   File "/usr/lib/python3.9/py_compile.py", line 215, in <module>
#0 40.86     sys.exit(main())
#0 40.86   File "/usr/lib/python3.9/py_compile.py", line 207, in main
#0 40.86     compile(filename, doraise=True)
#0 40.86   File "/usr/lib/python3.9/py_compile.py", line 172, in compile
#0 40.86     importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
#0 40.86   File "<frozen importlib._bootstrap_external>", line 126, in _write_atomic
#0 40.86 PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/__pycache__/__future__.cpython-39.pyc.140667885736320'
#0 40.86 dpkg: error processing package python3.9-minimal (--configure):
#0 40.86  installed python3.9-minimal package post-installation script subprocess returned error exit status 1
#0 40.88 Errors were encountered while processing:
#0 40.88  python3.9-minimal
#0 40.98 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y     chromium-driver firefox-esr     ca-certificates]: exit code: 100

docker has root access, as exemplified by the test command 'docker run hello-world, so I'm not sure what's up?

**Comment by Qoyyuum** [comment]
@Gnomesong its very likely that your docker set up isn't set correctly. Try this [StackOverflow solution](https://stackoverflow.com/a/68464690/1431104)

**Comment by giorgiogiudice** [comment]
same issue here.

**Comment by ianbmacdonald** [comment]
Feels like a bit of out of your comfort zone for the environment setup.   I am guess you are not running a debian based OS so those errors are coming from inside your docker image build which does use a Debian image for the main environment, and an Alpine linux image for execution of python code.  

Start with what versions of python and docker you are running locally.  I don't think 3.9 is going to cut it except for running python code inside spawned docker images;  Current docker is "docker compose" instead of "docker-compose" so you are probably out of date there too.  Thought I really have no idea what has been packaged up as stable or current for Windows. 

Confirm your autogpt branch, local python and docker versions, and output your running docker containers and images;  I have a feeling you may have some image and container cruft to deal with as well. 

Personally I find Debian 12 vms to be ideal as they can include packaged docker 5:24.01 and python 3.11.2 even though the official release for 12 is pending for June.  I have not had any issues running natively inside virtualenv to allow picking and choosing of differen python module versions that can have a python 3.11 dependency to wrap autogpt with, or inside spawned docker images which have a fixed 3.10 dependency from their Debian base image.  Both methods seem to effortlessly run python in the alpine build they pull by default (which does use the even older but more stable 3.9 python inside) .

```
(autogpt1) autoai:/usr/local/src/Auto-GPT-stable# dpkg -l | grep docker
ii  docker-buildx-plugin            0.10.4-1~debian.12~bookworm    amd64        Docker Buildx cli plugin.
ii  docker-ce                       5:24.0.1-1~debian.12~bookworm  amd64        Docker: the open-source application container engine
ii  docker-ce-cli                   5:24.0.1-1~debian.12~bookworm  amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras       5:24.0.1-1~debian.12~bookworm  amd64        Rootless support for Docker.
ii  docker-compose-plugin           2.18.1-1~debian.12~bookworm    amd64        Docker Compose (V2) plugin for the Docker CLI.
(autogpt1) autoai:/usr/local/src/Auto-GPT-stable# docker images
REPOSITORY         TAG        IMAGE ID       CREATED        SIZE
my-own-autogpt     latest     ad320fcc434a   10 hours ago   1.71GB
autogpt-upstream   latest     102821c3d2da   10 hours ago   1.71GB
python             3-alpine   6d5a91efe4ff   13 hours ago   77.4MB
ppm-old            latest     21a2f2def1ee   19 hours ago   1.66GB
(autogpt1) autoai:/usr/local/src/Auto-GPT-stable# 
(autogpt1) autoai:/usr/local/src/Auto-GPT-stable# dpkg -l | grep python3
ii  libpython3-dev:amd64            3.11.2-1+b1                    amd64        header files and a static library for Python (default)
ii  libpython3-stdlib:amd64         3.11.2-1+b1                    amd64        interactive high-level object-oriented language (default python3 version)
ii  libpython3.11:amd64             3.11.2-6                       amd64        Shared Python runtime library (version 3.11)
```

**Comment by renzocastillo** [comment]
Hi:

Similar situation over here where running `docker compose build auto-gpt`

```
#0 53.83 Preparing to unpack .../12-python3.11-minimal_3.11.2-6_amd64.deb ...
#0 53.83 Unpacking python3.11-minimal (3.11.2-6) ...
#0 53.98 Setting up libpython3.11-minimal:amd64 (3.11.2-6) ...
#0 53.99 Setting up python3.11-minimal (3.11.2-6) ...
#0 54.07 [Errno 13] Permission denied: '/usr/lib/python3.11/__pycache__/__future__.cpython-311.pyc.139813372983344'dpkg: error processing package python3.11-minimal (--configure):
#0 54.07  installed python3.11-minimal package post-installation script subprocess returned error exit status 1
#0 54.07 Errors were encountered while processing:
#0 54.07  python3.11-minimal
#0 54.11 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y     chromium-driver firefox-esr ca-certificates     && apt-get clean && rm -rf /var/lib/apt/lists/*]: exit code: 100
```

A few considerations:

- Docker correctly installed, at least according to the basic hello-world container example.
-  Already checked the thread mentioned by @Qoyyuum [here](https://github.com/Significant-Gravitas/Auto-GPT/issues/4296#issuecomment-1555903080) and assigned ownership to docker user. 
-   Using stable branch: 0.04 latest release. 

Am I missing something here . Thank for your help as I'm new to docker and not sure if I'm missing something here.

**Comment by renzocastillo** [comment]
> Hi:
> 
> Similar situation over here where running `docker compose build auto-gpt`
> 
> ```
> #0 53.83 Preparing to unpack .../12-python3.11-minimal_3.11.2-6_amd64.deb ...
> #0 53.83 Unpacking python3.11-minimal (3.11.2-6) ...
> #0 53.98 Setting up libpython3.11-minimal:amd64 (3.11.2-6) ...
> #0 53.99 Setting up python3.11-minimal (3.11.2-6) ...
> #0 54.07 [Errno 13] Permission denied: '/usr/lib/python3.11/__pycache__/__future__.cpython-311.pyc.139813372983344'dpkg: error processing package python3.11-minimal (--configure):
> #0 54.07  installed python3.11-minimal package post-installation script subprocess returned error exit status 1
> #0 54.07 Errors were encountered while processing:
> #0 54.07  python3.11-minimal
> #0 54.11 E: Sub-process /usr/bin/dpkg returned an error code (1)
> ------
> failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y     chromium-driver firefox-esr ca-certificates     && apt-get clean && rm -rf /var/lib/apt/lists/*]: exit code: 100
> ```
> 
> A few considerations:
> 
>     * Docker correctly installed, at least according to the basic hello-world container example.
> 
>     * Already checked the thread mentioned by @Qoyyuum [here](https://github.com/Significant-Gravitas/Auto-GPT/issues/4296#issuecomment-1555903080) and assigned ownership to docker user.
> 
>     * Using stable branch: 0.04 latest release.
> 
> 
> Thank for your help as I'm new to docker and not sure if I'm missing something here.

Ok found my own solution. Seemed the problem was I installed docker using snap installation at my Ubuntu 23 distro rather than actually using an apt installation or an docker desktop .deb installation . I completely purged my previous docker installation and installed it through the .deb file according to [this guide ](https://docs.docker.com/desktop/install/ubuntu/) and now auto-gpt has completely build correctly :)

**Comment by Prakhar-998** [comment]
I am getting similar issue while docker composing.

 => CACHED [migrate builder  3/17] RUN echo 'Acquire::http::Pipeline-Depth 0;\nAcquire::http::No-Cache true;\nAcquire::BrokenProxy true;\n' > /etc/apt/apt.conf.d/99fixbadproxy                            0.0s
 => CACHED [migrate builder  4/17] RUN apt-get update --allow-releaseinfo-change --fix-missing                                                                                                             0.0s 
 => ERROR [migrate builder  5/17] RUN apt-get install -y build-essential                                                                                                                                   0.8s 
------
 > [migrate builder  5/17] RUN apt-get install -y build-essential:
0.744 Reading package lists...
0.773 Building dependency tree...
0.775 Reading state information...
0.779 E: Unable to locate package build-essential
------
failed to solve: process "/bin/sh -c apt-get install -y build-essential" did not complete successfully: exit code: 100
