### ISSUE TITLE
Send code to analyze without the code

### ISSUE THREAD

**Issue by giladsho** [Significant-Gravitas/Auto-GPT#4442]
### ⚠️ Search for existing issues first ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

when using the command `analyze_code`, its send no code. 

NEXT ACTION:  COMMAND = analyze_code ARGUMENTS = {'code': '<full_code_string>'}

its happened a quite few times.

**Comment by zachRadack** [comment]
I got the something similar

when testing it code, it seems to sometimes not put the actual code inside but rather statements such as "'I will analyze the code manually to ensure that it is functioning properly"

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/104032269/b208d46c-2c8c-48af-b6a1-478513f847d8)

here is inital prompt

`create a html webpage that visualizes swarm intellegence by utilizing "screaming insects" algorithem. Make it visualy simple, make it has little food nodes that move from one side of the screen to the other and when they collide with edge of the webpage, it despawns and a new one spawns else somewhere randomly. Make 3 little "insect nests" that spawn in random spots at the start and slowly bounce around the webpage. there will be many insects who are strictly loyal to their starting nests and try to deliever food to only their nest.`

here is actual log, near the end I did add a little part because it can not actually test what I want, due to the nature of it, but either way.

[activity.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11619566/activity.log)
