### ISSUE TITLE
What makes the AutoGPT thinking time slow?

### ISSUE THREAD

**Issue by WeihanWMW** [Significant-Gravitas/Auto-GPT#4443]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

```
Distributor ID:	Ubuntu

Description:	Ubuntu 22.04.2 LTS

Release:        22.04

Codename:	jammy

My AutoGPT version: v0.3.1
```

Why is the Thinking time slow and what can be done to improve it? Iam using AutoGPT with GPT-3.5 and a Redis backend.

There seems to be no significant load on my computer, however the thinking time is still slow.

Best Regards,
Configentia

**Comment by k-boikov** [comment]
Here is how you can check if there is some bottleneck on your machine:
Instead of running ./run.bat (or ./run.sh) you can run:
`python -m cProfile -o profile.pickle -m autogpt`

That will start Auto-GPT and you should run it for some time. After you are done you will have a profiler data that you can export using this script:
```python
import pstats

# Load the profiling data from the profile.txt file
profile_data = pstats.Stats('profile.pickle')

# Print the profiling statistics
profile_data.strip_dirs().sort_stats('cumulative').print_stats()
```

If you save it as read_profile.py you can run:
```python read_profile.py > profile_output.txt```

In profile_output.txt you will have all the functions ordered by how long they have taken to execute. Here is my top N functions that have cumulatively taken more than 2 seconds:

<details>
<summary>Details</summary>
<code>
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1634/1    0.024    0.000  308.301  308.301 {built-in method builtins.exec}
        1    0.000    0.000  308.301  308.301 <frozen runpy>:201(run_module)
        1    0.000    0.000  308.266  308.266 <frozen runpy>:65(_run_code)
        1    0.000    0.000  308.266  308.266 __main__.py:1(<module>)
        1    0.000    0.000  308.235  308.235 core.py:1128(__call__)
        1    0.000    0.000  308.235  308.235 core.py:987(main)
        1    0.000    0.000  308.233  308.233 core.py:1623(invoke)
        1    0.000    0.000  308.233  308.233 core.py:1393(invoke)
        1    0.000    0.000  308.233  308.233 core.py:709(invoke)
        1    0.000    0.000  308.233  308.233 decorators.py:25(new_func)
        1    0.000    0.000  308.233  308.233 cli.py:5(main)
        1    0.000    0.000  305.876  305.876 main.py:26(run_auto_gpt)
        1    0.001    0.001  295.029  295.029 agent.py:86(start_interaction_loop)
        8    0.000    0.000  209.966   26.246 sessions.py:502(request)
        8    0.000    0.000  209.949   26.244 sessions.py:673(send)
       25    0.000    0.000  209.634    8.385 socket.py:692(readinto)
       25    0.000    0.000  209.633    8.385 ssl.py:1267(recv_into)
       25    0.000    0.000  209.633    8.385 ssl.py:1125(read)
       25  209.633    8.385  209.633    8.385 {method 'read' of '_ssl._SSLSocket' objects}
        8    0.000    0.000  209.629   26.204 adapters.py:434(send)
        8    0.000    0.000  209.622   26.203 connectionpool.py:522(urlopen)
        8    0.000    0.000  209.618   26.202 connectionpool.py:361(_make_request)
      293    0.000    0.000  209.601    0.715 {method 'readline' of '_io.BufferedReader' objects}
        8    0.000    0.000  209.321   26.165 client.py:1331(getresponse)
        8    0.000    0.000  209.320   26.165 client.py:311(begin)
        8    0.000    0.000  209.316   26.165 client.py:278(_read_status)
        5    0.000    0.000  208.609   41.722 api_requestor.py:205(request)
        5    0.000    0.000  208.609   41.722 api_requestor.py:497(request_raw)
        3    0.000    0.000  208.557   69.519 chat.py:22(chat_with_ai)
        4    0.000    0.000  208.023   52.006 __init__.py:47(metered_func)
        4    0.000    0.000  208.020   52.005 __init__.py:81(_wrapped)
        4    0.000    0.000  208.020   52.005 __init__.py:184(create_chat_completion)
        4    0.000    0.000  208.020   52.005 api_manager.py:30(create_chat_completion)
        4    0.000    0.000  208.019   52.005 chat_completion.py:12(create)
        4    0.000    0.000  208.019   52.005 engine_api_resource.py:127(create)
        5   73.826   14.765   73.826   14.765 {built-in method builtins.input}
        4    0.000    0.000   70.468   17.617 utils.py:29(clean_input)
      130    0.001    0.000   21.045    0.162 __init__.py:1610(_log)
      214    0.001    0.000   21.036    0.098 __init__.py:1544(log)
      130    0.000    0.000   21.034    0.162 __init__.py:1636(handle)
      130    0.001    0.000   21.033    0.162 __init__.py:1690(callHandlers)
      260    0.001    0.000   21.032    0.081 __init__.py:965(handle)
       53    0.000    0.000   21.017    0.397 logs.py:87(typewriter_log)
       53    0.037    0.001   21.001    0.396 logs.py:189(emit)
     2512   20.589    0.008   20.589    0.008 {built-in method time.sleep}
        3    0.000    0.000   13.122    4.374 logs.py:254(print_assistant_thoughts)
      206    0.006    0.000   10.894    0.053 __init__.py:1(<module>)
        2    0.000    0.000    7.934    3.967 message_history.py:51(trim_messages)
        1    0.000    0.000    7.934    7.934 message_history.py:123(update_running_summary)
        1    0.000    0.000    5.386    5.386 prompt.py:49(construct_main_ai_config)
        1    0.000    0.000    3.373    3.373 plugins.py:203(scan_plugins)
        1    0.000    0.000    3.359    3.359 plugins.py:258(denylist_allowlist_check)
  1991/20    0.015    0.000    2.844    0.142 <frozen importlib._bootstrap>:1167(_find_and_load)
  1982/18    0.011    0.000    2.843    0.158 <frozen importlib._bootstrap>:1122(_find_and_load_unlocked)
  1661/18    0.009    0.000    2.839    0.158 <frozen importlib._bootstrap>:666(_load_unlocked)
  1500/18    0.004    0.000    2.838    0.158 <frozen importlib._bootstrap_external>:934(exec_module)
  4021/38    0.003    0.000    2.834    0.075 <frozen importlib._bootstrap>:233(_call_with_frames_removed)
        5    0.000    0.000    2.407    0.481 main.py:1(<module>)
   653/99    0.001    0.000    2.171    0.022 {built-in method builtins.__import__}
        1    0.000    0.000    2.121    2.121 agent.py:1(<module>)
        1    0.000    0.000    2.075    2.075 app.py:1(<module>)
</code>
</details>

My stats show that my program ran for 305.876s (run_auto_gpt), out of them 73.826s were spent waiting for me to type some input (I was slow, because I was doing something else in parallel), 21.045s were spent typewriting something to the console (20.589s of them to sleep in between typing letters) and 209.966s for "request" aka the communication with OpenAI. So for me the biggest bottleneck is OpenAI's API. Is that the case for you?
