### ISSUE TITLE
Auto-gpt executes python code successfully but does not generate .png file

### ISSUE THREAD

**Issue by jordanshirley96** [Significant-Gravitas/Auto-GPT#4571]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux/Ubuntu

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

I've instructed autogpt to execute the file pizza.py. The code generates an image of a pizza as a .png file in the auto_gpt_workspace directory. 

Autogpt can create and execute the code without error, and additionally it prints a message at the end of the file, indicating it worked it's way through the code. However, this code specifically generates a .png image which is nowhere to be found after it runs the code. When I manually run the code with python3 pizza.py, it successfully generates the image of the pizza in the auto_gpt_workspace folder. I think this issue has something to do with the docker container, as I am using docker-compose, but I am unsure.

Anybody know how to resolve this issue?

**Comment by lc0rp** [comment]
Here are some suggestions to help debug the issue:
- Try running with the flag --debug and review the logs in the /logs directory.
- Check the file_logger.txt in the workspace directory for any potential errors.
- Consider adding additional debug hooks into the pizza.py file.

**Comment by Dr33dM3** [comment]
Based on the provided information, it seems that the issue you're facing is likely due to running Auto-GPT outside a containerized environment, such as Docker. The documentation explicitly states that executing Python scripts is disabled in non-container environments to maintain system and data security.

To address this problem, you have a couple of options:

    Modify the pizza.py code so that it generates the image without relying on executing Python scripts or writing files in the auto_gpt_workspace folder. Here's an example of how you can achieve this:

python

import matplotlib.pyplot as plt

# Generate your pizza image using matplotlib or any other library
pizza_image = ...  # Generate the image here

# Save the image to a specific location
image_path = "/path/to/desired/location/pizza.png"
plt.imsave(image_path, pizza_image)

# Print a message to indicate successful generation
print("Pizza image generated successfully!")

By modifying the code in this way, you can specify the exact location where the pizza image should be saved, regardless of the execution environment.

    Alternatively, you can run Auto-GPT within a containerized environment, such as Docker. Containers provide the necessary permissions to write files in the desired folder.

**Comment by Dr33dM3** [comment]
Based on the provided information, it seems that the issue you're facing is likely due to running Auto-GPT outside a containerized environment, such as Docker. The documentation clearly states that executing Python scripts is disabled in non-container environments to maintain system and data security.

To address this problem, you have a couple of options:

    Modify the pizza.py code so that it generates the image without relying on executing Python scripts or writing files in the auto_gpt_workspace folder.

    Run Auto-GPT within a containerized environment, like Docker, where the necessary permissions are granted to write files in the specified folder.

**Comment by Boostrix** [comment]
If that's the case, the OP could also directly execute python via the shell

**Comment by jordanshirley96** [comment]
Yes I am running inside a Docker container. When I run my script directly
with a /bin/bash inside the docker container it outputs the .png file. The
issue is when autogpt itself runs the script.
