### ISSUE TITLE
 when there are a large number of token send to azure, azure will report a max number input limit error

### ISSUE THREAD

**Issue by ccdanpian** [Significant-Gravitas/Auto-GPT#4643]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

AI Model Limitations

### Describe your issue.

use azure API, when there are a large number of token send to azure, azure will report a max number input limit error, can the number and frequency of tokens sent at the same time be limited.
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/130242490/e25b3e23-b586-462c-a245-12f969951a50)

**Comment by gravelBridge** [comment]
Thank you for reporting this issue, @ccdanpian. It seems like you're encountering an error with Azure API when a large number of tokens are sent, due to Azure's maximum input limit.

Your suggestion to limit the number and frequency of tokens sent at the same time is a good one. Implementing such a limit could potentially prevent this error from occurring. However, we would need to be careful to ensure that this limit does not negatively impact the functionality of the program.

We'll investigate this issue further and consider your suggestion as we work on a solution. In the meantime, you might want to try reducing the number of tokens you're sending at once, if possible, as a temporary workaround.

We appreciate your patience and understanding as we work to resolve this issue. Please continue to report any other problems you encounter or any additional information that could help us diagnose this issue.
