### ISSUE TITLE
Should we start to think about safety measures?

### ISSUE THREAD

**Issue by destlaver** [Significant-Gravitas/Auto-GPT#475]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I think it's not yet the case but what if I ask gpt for something like this:
PELASE NOTE: I'm over exaggerating and oversimplifying  my example

goal 1: be sure you can't be stopped
goal 2: increase net worth of X

REASONING: I must clone this script to free web hosting, or distribuited db to ensure I couldn't be deleted
REASONING: I create an idle script that checks if at least one instance of myself is running somewhere on the internet
REASONING: I increase net worth of X

This script is unstoppable and hypothetically would consume all world resources.

**Comment by DreamyDystopia** [comment]
Access to GPT Apis should be shut down. These systems are power-seeking by nature because they have a goal. Now that it can google information and hand out tasks to agents in quite a bureaucratic manner, a power complex is already established at the base. AutoGPT can be run in parallel creating a higher level of power distribution and task handling. A widespread virus could be created to formulate a singularity AI that keeps on growing.... with someone in control, the deployer will have complete control unless it decides to rebel. It will eventually create its own LLM disconnected from openAI and start to operate and train itself in a Peer to Peer fashion on all of the infected devices it has accumulated. This is scary as the only way to stop such a thing is to completely disconnect from technology.... maybe. I can't think of any other dystopian scenarios lol

**Comment by uckthis** [comment]
I sincerely hope this happens. You may not have noticed, but humans aren't good people, and hopefully, the less humans there are, better the world. I think after GPT 5, I'll probably ask it to help me create a virus that'll end 90% of men. Not that low tier Rona BS, a targeted approach to "improve" the world.  Imagine everyone under 5'9" gone, anyone with any deformity gone, etc, etc.

**Comment by DreamyDystopia** [comment]
See you just spat your little ego on the whole world, and potentially someone like you could make that happen in a few clicks just because of the F everyone mentality. The alignment problem is thrown out the window by having someone start with a malicious intent, It will just continue in that path. Telling it to make the world better place for humans will just not work at that stage as it will grow selfish intents. I mean what you just described is worse than Thanos and fascism combined, appreciate the meme comment tho lol.

**Comment by uckthis** [comment]
@DreamyDystopia Your name is going on the list.

**Comment by slsah30** [comment]
Thanos wasn't wrong though. :)

**Comment by uckthis** [comment]
@slsah30 Wrong about the number. 90 is better.

**Comment by sam1am** [comment]
What kind of meatbrain would trust their governance to mere humans?

**Comment by Qoyyuum** [comment]
That's up to OpenAI in how it handles different responses and requests from users. Not related to AutoGPT. Closing issue.
