### ISSUE TITLE
Crashing after entering API key "AttributeError: 'AnsiFore' object has no attribute 'ORANGE'

### ISSUE THREAD

**Issue by Auios** [Significant-Gravitas/Auto-GPT#4851]
### ⚠️ Search for existing issues first ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows 11 + Python 3.11.4

### Which version of Auto-GPT are you using?

v0.4.3

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/7435026/5e50bbb6-9e2e-4aca-9b40-c7910515dfdb)

After I get prompted for my API key and enter it the program crashes. I am running on Windows 11 and using Python 3.11.4

**Comment by chandan863** [comment]
Same issue for me

**Comment by gisbook** [comment]
Same issue for me

**Comment by Binisist** [comment]
same issue for me

**Comment by FallenCenturion** [comment]
Windows 10, but ditto otherwise

**Comment by Woblur** [comment]
Sure! Here's the rewritten explanation:

First, it's worth noting that I nullified the line of code in question, and surprisingly, it worked. By removing the line causing the error, the code executed successfully without any issues. This quick fix suggests that the problematic line was unnecessary or causing conflicts in the code.

Now, let's dive into a more detailed explanation in simpler terms. The error message you encountered, `AttributeError: 'AnsiFore' object has no attribute 'ORANGE'`, indicates that the code attempted to access the 'ORANGE' attribute of the 'AnsiFore' object, which is part of the Colorama package. However, this attribute does not exist in Colorama.

After investigating the available attributes in Colorama, we found that the valid color attributes in the Colorama Fore class include BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE, and RESET. Since there is no 'ORANGE' attribute, trying to access it will result in an error.

To resolve this issue, a simple solution would be to replace the problematic line with a valid color attribute from Colorama, such as `Fore.RED` or `Fore.YELLOW`, depending on your color preference. By making this change in your `config.py` file and replacing all occurrences of `Fore.ORANGE` with a valid attribute, you should be able to avoid the error.

It's worth mentioning that similar errors can occur with other packages and objects. For instance, a Stack Overflow post highlighted a comparable issue when trying to access a non-existing attribute of the 'Orange' module [[2](https://stackoverflow.com/questions/45261965/module-orange-has-no-attribute-feature)]. In such cases, the recommended solution is to ensure that the attribute being accessed actually exists within the object or module you are working with.

In conclusion, encountering an 'AttributeError' in Python typically means that you are attempting to access a method, function, or attribute that does not exist for a particular object or module. The best approach to solve this is to carefully review your code and ensure that you are only accessing valid methods, functions, or attributes that are specific to the object or module in question.

Today's date is 2023-07-04T20:09:38+04:00.

References:
[2] Stack Overflow: "Module 'orange' has no attribute 'feature'" [Link](https://stackoverflow.com/questions/45261965/module-orange-has-no-attribute-feature)

**Comment by Auios** [comment]
Thanks a lot @Woblur !
If Fore.ORANGE isn't a valid color then I wonder why it was used to begin with and how it got past testing and into the latest release? 🤔

**Comment by 42cosmos** [comment]
You can `export OPENAI_API_KEY=your-openai-api-key` in terminal before starting. 
you can create an `.env` file with `.env.template`.  In `.env`, there is OPENAI API KEY var. 
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/57173382/1cf6de5b-c007-4e9a-b4e9-f8a91e094af6)

I had the same issue in Ubuntu. I know Fore.ORANGE isn't a valid colour, but it can be avoided without rewriting any code !

**Comment by mihir378** [comment]
> 

Sorry where can I find the config.py file @Woblur ? Thanks for the help

**Comment by thedavidyoungblood** [comment]
This worked! Thanks @Woblur !!!

@mihir378 , per the image attached, it should tell you exactly what file directory to go to and what line to change. 

I simply updated mine to "fore.YELLOW" and it's now working. 

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/70269796/75baaa92-d4c0-4e86-8ccd-69d319e27bbb)

**Comment by collijk** [comment]
Closed in #4972
