### ISSUE TITLE
Unable to use AutoGPT with voice

### ISSUE THREAD

**Issue by udaykumar1997** [Significant-Gravitas/Auto-GPT#4926]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Main branch.

### Do you use OpenAI GPT-3 or GPT-4?

I use both GPT-3.5 and GPT-4. However, this issue is independent of the GPT model used. 

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I've tried running AutoGPT with `--speak` parameter on Docker, VSCode Containers, and also directly via python. The issue persists in all cases. 
I've tried on the latest stable version and on the master version. In the latest stable version, we get the error `TypeError: say_text() missing 1 required positional argument: 'config'` which has been fixed in #4794. But the main branch still seems to be plagued with a variant of this issue.

I get the error `sh: 1: say: not found` and no voice.

Please let me know if you need any additional details.

**Comment by Ian-Vallely** [comment]
I'm getting the same error msg

**Comment by K-Diderot** [comment]
I ran into a similar issue, specifically in relation to Eleven Labs.

So if anyone comes across this one:

To resolve the --speak issue that I was running into, I did the following:
Edit: Auto-GPT\autogpt\speech\eleven_labs.py
ADD this code, below line 45:

if 'elevenlabs_voice_2_id' in config:

and since I don't know python [stop judging me!], add an indent to the two lines of code following your inserted line[now lines 47,48]

Then move line 50 above line 49:
        self._use_custom_voice(config.elevenlabs_voice_id, 0)
        self._use_custom_voice(config.elevenlabs_voice_2_id, 1)
to 
        self._use_custom_voice(config.elevenlabs_voice_2_id, 1)
        self._use_custom_voice(config.elevenlabs_voice_id, 0)

finally indenting twice what is now line 49 to, ostensibly, place it within the scope of the preceding if statement :)


ultimately resulting in this:
```python
if config.elevenlabs_voice_id in voice_options:
            config.elevenlabs_voice_id = voice_options[config.elevenlabs_voice_id]
        if 'elevenlabs_voice_2_id' in config:
            if config.elevenlabs_voice_2_id in voice_options:
                config.elevenlabs_voice_2_id = voice_options[config.elevenlabs_voice_2_id]
                self._use_custom_voice(config.elevenlabs_voice_2_id, 1)
        self._use_custom_voice(config.elevenlabs_voice_id, 0)
``` 
    
I've gone overboard on the instructions because I honestly don't know if a simple copy & paste of python code would be problematic, due to it's tab dependent logic.  

Anywho, soo long suckers.

**Comment by udaykumar1997** [comment]
@K-Diderot thanks for sharing. Do you know if there's a PR submitted for this? If not, can we submit one?

**Comment by K-Diderot** [comment]
I'm hesitant to make a pull request since my python experience begins and ends with the elevenlab.py file.  Honestly, I would be concerned that committing my solution would be akin to banging on some pots and pans, calling it my Opus, and saying You're Welcome. 
:) Well... over the top but you get the point.
