### ISSUE TITLE
Framework for optional features

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#645]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We should make some framework for optional features, so that they:

- don't make default configuration harder for newcomers
- don't bloat .env.template
- don't bloat the prompt
- don't bloat the README

### Examples 🌈

Well, people add commands all the time.

### Motivation 🔦

The setup should be very easy for newcomers, with just very bare bones configuration. Preferrably, only the model itself.

And optional features should be modular, with additions to the prompt and to the command registry and to the config.

Maybe we should have a provision for OS-specific features, such as OS-specific TTS (both Windows and MacOS have built-in TTS, as an example).

**Comment by Wladastic** [comment]
It would be great to have a config file too, not just everything inside the .env as I would assume the environment vars are more important and less optional than just config.

Right now, my feedback as a newcomer:
It is already really hard to tell what is mandatory and what is not, because the Readme first states some basic setup, then continues to explain stuff like setting up redis etc. without a clear cut of what shall be done and what not.

Even Bing Chat got confused and tried to convince me to setup a huggingface api and have redis run on an azure server lol

**Comment by Ghee36** [comment]
Indeed.  It's amazing to get this running for experiments and exploration without too much familiarity. 
Though with limited experience I regret trying to figure out the new Redis changes by following the Readme, and probably will optionally avoid Redis throughout once I also remove Docker.

**Comment by ntindle** [comment]
See https://github.com/Significant-Gravitas/Auto-GPT/pull/757#issuecomment-1512395642 and https://github.com/Significant-Gravitas/Auto-GPT/pull/757#issuecomment-1512426726
