### ISSUE TITLE
Not creating pinecone index

### ISSUE THREAD

**Issue by Lucyan11** [Significant-Gravitas/Auto-GPT#711]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I by mistake deleted my pinecone index.  When i fire up auto-gpt it does not make me a new one but functions correctly.  I have tried starting fresh, but same issue. Works fine but is not triggering pinecone.

### Current behavior 😯

i download a fresh copy and fill in the .env and it starts but does not create a pinecone index.

### Expected behavior 🤔

Every other time ive loaded it it creates the index and then communicates with it.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by LericDax** [comment]
Pinecone seems to take a while to clear the file. Check everything and try it again, if you would? I had a similar experience but it dumped after a while and I was able to reinitialize a new index.

**Comment by crimson-knight** [comment]
I just started with this script today, brand new Pinecone account and it never created the Pinecone index ever

**Comment by crimson-knight** [comment]
I figured it out, there is a new ENV var that needs to be configured `MEMORY_BACKEND` that was introduced in #372 

It'll default to using local cache for memory, which gets a little ADHD I've noticed.

You can configure the memory to accept:

`local` (the default)
`redis`
`pinecone`

Redis is giving me errors currently, but Pinecone and LocalCache work fine

**Comment by crimson-knight** [comment]
@sjnt1 you can just add the env var into the .env file and it'll work

You don't need to configure anything in Pinecone, let AutoGPT do it.

I found localcache gets a little ADHD when starting/stopping and Pinecone has been much better for memory across multiple agents.

I'm currently getting errors with Redis, it does work but the index errors. I haven't bothered to diagnose it because I'm not going to use it 🤷‍♂️

**Comment by crimson-knight** [comment]
@sjnt1 As I said in my previous comment, you are not supposed to create the index because AutoGPT does it for you. Delete it, and then re-run Auto-GPT and it will create what it needs.

**Comment by sjnt1** [comment]
Sorry. I'm kinda overwhelmed with information and other stuff so i get tunnel sight. I had to re-run it a couple of times after deleting the index for it to work. But now it does, so ty again. I cant tell the difference yet tho, if anything it has a harder time summarizing alot of chunks at a time than before, 

Can i ask if you or anyone else know the reason for why it thinks so fast on some YT videos? But for me it takes like 10x slower. Can it be since they have gpt4 API access? I've read that GPT+ and the API key don't have anything to do with each other and i have ok computer so it shouldnt take that long for it to think.
