### ISSUE TITLE
Add command for editing files in place

### ISSUE THREAD

**Issue by loliverhennigh** [Significant-Gravitas/Auto-GPT#727]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently Auto-GPT writes the entire python or text file at once. If the file gets beyond a few paragraphs this starts to cause issues often time causing json parsing error. Could we somehow have it insert text into an existing file. Maybe we can have it give vim commands to edit it.

Been running a benchmark of having it write a fluid simulation using the lattice boltzmann method. Been running this everyday for a week or so to see the progress of Auto-GPT developments. I think it is very close to working but need this one last bit of functionality.

### Examples 🌈

Here is an example that I think shows gpt is capable of doing it.
![Screenshot from 2023-04-10 12-03-14](https://user-images.githubusercontent.com/4978408/230974929-033d978a-7ede-4bd4-b8dc-d6709afccfb8.png)

![Screenshot from 2023-04-10 12-02-52](https://user-images.githubusercontent.com/4978408/230974919-dad15015-8279-42a5-99d9-5d3094edc19f.png)

### Motivation 🔦

This would allow for Auto-GPT to modify and improve itself

**Comment by Boostrix** [comment]
> This would allow for Auto-GPT to modify and improve itself: https://github.com/Significant-Gravitas/Auto-GPT/issues/15

I have seen it using sed/awk successfully - but it does help to update its constraints to prefer CLI line editors. Also, like you said, the invalid JSON issue is more likely once the file to be modified becomes larger.  I tried to make it work off diff/patches, but that breaks currently because those are using hashes to reference local files, so one would probably need a new mode to create/edit a diff and use CLI tools to update the hash portion, and only let the LLM handle the rest, i.e. coming up with code.

For the time being, changes that are spanning multiple files but that are conceptually related (as in adding new commands/actions to Auto-GPT), is hitting too many hard-coded constraints - not to mention the contex window restriction
