### ISSUE TITLE
Reading files work, execution doesn't (Docker)

### ISSUE THREAD

**Issue by Nickonomic** [Significant-Gravitas/Auto-GPT#807]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Lots of posts of not being able to read a .py file. My docker can read it but unable to execute (file not found). Clearly, there is a confusion inside the function between /auto-gpt-workspace and /workspace dirs. os may not work properly inside Docker too.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by PHONGTHIEUHON** [comment]
Have you tried to port current directory to docker when you run it?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Nickonomic ***@***.***>
Sent: Tuesday, April 11, 2023 10:50:28 PM
To: Torantulino/Auto-GPT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Torantulino/Auto-GPT] Reading files work, execution doesn't (Docker) (Issue #807)


Duplicates

  *    I have searched the existing issues

Steps to reproduce 🕹

No response

Current behavior 😯

Lots of posts of not being able to read a file. My docker can read it but unable to execute. Clearly, there is a confusion inside the function between /auto-gpt-workspace and /workspace dirs. os may not work properly inside Docker too.

Expected behavior 🤔

No response

Your prompt 📝

# Paste your prompt here

**Comment by Nickonomic** [comment]
No. Not sure how to do it properly. 
I've actually got rid of Docker altogether in the code.

**Comment by Pwuts** [comment]
Please try again with the latest version and reopen if the problem persists. Closing as resolved.
