### ISSUE TITLE
Implement versioning and a changelog

### ISSUE THREAD

**Issue by richbeales** [Significant-Gravitas/Auto-GPT#854]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We should have a Semantic versioning (semver.org) version number, and increment it appropriately.
We should also maintain a high-level changelog, either in code or in the discord, allowing users to track what's new/changed.

Downsides : Extra effort to maintain.

### Motivation 🔦

Would make it easier for users to track progress / what's changed without needing to read through the commit log.

**Comment by ehizman** [comment]
I can work on this

**Comment by zenflow** [comment]
There are tools to do this kind of thing (determine next version number according to semver, generate changelog, create tag in git / release on GitHub) automatically based on semantic commit messages: https://python-semantic-release.readthedocs.io/en/latest/ and I'm sure there are many others. 

But I think they work better on projects that are python packages.

That said, why isn't this project a program published as a package on PyPI?

**Comment by Boostrix** [comment]
Based on playing with @coleyr's idea https://github.com/Significant-Gravitas/Auto-GPT/issues/15#issuecomment-1500873425 of using a Python script to traverse PRs and issues, we're probably in a position to automate some of this: https://github.com/Significant-Gravitas/Auto-GPT/compare/master...Boostrix:Auto-GPT:topic/PRHelper.py
 

At this stage, an Auto-GPT plugin would be quite capable of looking at commit logs and the corresponding PRs to come up with drafts for the changelog (most commit messages and PR talks would fit into the 4k ctx window) - these changelog changes/suggestions themselves could be provided via a PR so that they're reviewed. 

But that's the sort of thing that GPT/Auto-GPT can automate for us.
We could even integrate that as a command/option so that volunteers can run this tool directly inside Auto-GPT to help review commits logs and make PRs to update a single Changelog file.

However, I do think in #15 someone mentioned a tool called "ReviewPad" probably handling most/all of this in an automated fashion already.
